# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Crystal Warden Supply Chain Labs LLC
"""Compile the 2-field fusion policy to a .ppt and emit it as a C header for the fusion-pod firmware.

Two independent analog fields fused into one decision: `level` (the potentiometer, 0-4095) and `light`
(the photoresistor, 0-4095). The interesting property is that the ALERT verdict depends on BOTH fields
together — knob set high AND the room dark — a fused region neither field reaches alone. Decided
on-device by the same byte-exact evaluator every substrate certifies; the winning edge index is the
verdict: 0=alert 1,2=warn 3=ok.

    python gen_fusion_table.py     # -> main/fusion_table.h
"""
import sys
from pathlib import Path

HW = Path(__file__).resolve().parent.parent          # prismpath-hw
REPO = HW.parent
sys.path.insert(0, str(HW))
sys.path.insert(0, str(REPO))

import ppt_compile as pc
from prismpath.parser import parse

FLOW = """---
name: fusion
start: classify
---
## classify
Two fields fused: knob position (level) and ambient light. Alert only when set high AND in the dark —
a region neither field reaches alone.
-> alert: when level >= 3000 and light < 1000
-> warn: when level >= 2048
-> warn: when light < 1000
-> ok: else
## alert
-> end: when always
## warn
-> end: when always
## ok
-> end: when always
## end
done
"""

VERDICTS = ["alert", "warn", "warn", "ok"]     # by classify edge index


def main() -> int:
    blob = pc.compile_flow(parse(FLOW), 25).serialize()
    hexb = ",\n  ".join(
        ", ".join(f"0x{b:02x}" for b in blob[i:i + 12]) for i in range(0, len(blob), 12))
    out = [
        "/* generated by gen_fusion_table.py — the embedded 2-field fusion policy .ppt (do not edit) */",
        "#ifndef FUSION_TABLE_H",
        "#define FUSION_TABLE_H",
        "#include <stdint.h>",
        f"static const uint8_t FUSION_TABLE[] = {{\n  {hexb}\n}};",
        f"static const uint16_t FUSION_TABLE_LEN = {len(blob)};",
        f'/* classify edge index -> verdict: {", ".join(f"{i}={v}" for i, v in enumerate(VERDICTS))} */',
        "#endif",
        "",
    ]
    (HW / "esp-fusion-pod" / "main" / "fusion_table.h").parent.mkdir(parents=True, exist_ok=True)
    (HW / "esp-fusion-pod" / "main" / "fusion_table.h").write_text("\n".join(out))
    print(f"wrote fusion_table.h: {len(blob)} bytes, verdicts by edge {VERDICTS}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
