// GENERATED by gen_spiral_mesh_data.py — role map + synthesis params
#pragma once
#include <stdint.h>
#define N_ROLES 3
// sidecar field order: pot, range_a, range_b
static const uint8_t ROLE_MAC[N_ROLES][6] = {
  {0x58, 0x2a, 0xbd, 0x76, 0x6a, 0xbc},
  {0x68, 0x09, 0x47, 0xdf, 0xd5, 0x90},
  {0x68, 0x09, 0x47, 0xe0, 0x38, 0x00},
};
static const uint8_t ROLE_FIELD[N_ROLES] = {1, 2, 0};
static const int32_t ROLE_SYNTH[N_ROLES][4] = {  // lo, hi, period, phase
  {100, 320, 20, 0},
  {120, 300, 26, 7},
  {400, 800, 34, 13},
};
