SIM ?= verilator
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES = $(PWD)/../rtl/ppt_ctrl_interp.sv
COCOTB_TOPLEVEL = ppt_ctrl_interp
COCOTB_TEST_MODULES = test_ppt_ctrl_interp
TOPLEVEL = $(COCOTB_TOPLEVEL)
MODULE = $(COCOTB_TEST_MODULES)
EXTRA_ARGS += -I$(PWD)/../rtl
include $(shell cocotb-config --makefiles)/Makefile.sim
