SIM ?= verilator
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES = $(PWD)/../rtl/ppt_axi_wmux.sv
COCOTB_TOPLEVEL = ppt_axi_wmux
COCOTB_TEST_MODULES = test_ppt_axi_wmux
TOPLEVEL = $(COCOTB_TOPLEVEL)
MODULE = $(COCOTB_TEST_MODULES)
include $(shell cocotb-config --makefiles)/Makefile.sim
