SIM ?= verilator
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES = $(PWD)/../rtl/ppt_field_ctrl.sv
COCOTB_TOPLEVEL = ppt_field_ctrl
COCOTB_TEST_MODULES = test_ppt_field_ctrl
TOPLEVEL = $(COCOTB_TOPLEVEL)
MODULE = $(COCOTB_TEST_MODULES)
include $(shell cocotb-config --makefiles)/Makefile.sim
