// GENERATED by gen_spiral_node_data.py — boundary probes + deterministic fill
#pragma once
#include <stdint.h>
#define TV_K 2
#define TV_N 20
// field order: level, range
static const int32_t TV[20][2] = {
  {299, 199},
  {299, 200},
  {300, 199},
  {300, 200},
  {867, 612},
  {267, 38},
  {242, 510},
  {841, 192},
  {890, 145},
  {736, 697},
  {433, 353},
  {348, 1013},
  {459, 342},
  {69, 328},
  {866, 178},
  {409, 246},
  {424, 1010},
  {64, 308},
  {421, 17},
  {161, 678},
};
