cmake_minimum_required(VERSION 3.13)
include(pico_sdk_import.cmake)
project(codec_bench C CXX ASM)
pico_sdk_init()
add_executable(rp_bench rp_bench.c)
target_include_directories(rp_bench PRIVATE ..)
target_link_libraries(rp_bench pico_stdlib)
pico_enable_stdio_usb(rp_bench 1)
pico_enable_stdio_uart(rp_bench 0)
pico_add_extra_outputs(rp_bench)
