#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Crystal Warden Supply Chain Labs LLC
"""Compile the room fusion policy for the host relay and emit main/fusion_policy.h: the table, the register map, the
node names, the two camera ids, and the masks over the camera policy's node indices that mean occupied and tamper,
derived from the camera flow's node names (never typed by hand).
    python gen_fusion_policy.py [fusion.md] [camera flow.md]"""
import sys
from pathlib import Path
HW = Path(__file__).resolve().parent.parent; REPO = HW.parent
sys.path.insert(0, str(HW)); sys.path.insert(0, str(REPO))
import ppt_compile as pc
from prismpath.kernel.parser import parse_file
if len(sys.argv) < 3: sys.exit("usage: gen_fusion_policy.py <fusion flow.md> <camera flow.md>   (this bench ran flows/room_fusion.md over esp-vision-node/flows/occupancy_6x8.md)")
flow, cam = sys.argv[1], sys.argv[2]
g = parse_file(flow); img = pc.compile_flow(g, 25); blob = img.serialize(); names = [n for n, _ in img.nodes]
cg = parse_file(cam); cimg = pc.compile_flow(cg, 25); cnames = [n for n, _ in cimg.nodes]
occ = sum(1 << i for i, n in enumerate(cnames) if n in ("occupied", "door", "evidence")); tam = sum(1 << i for i, n in enumerate(cnames) if n == "tamper")
hexb = ",\n  ".join(", ".join(f"0x{b:02x}" for b in blob[i:i + 16]) for i in range(0, len(blob), 16))
lines = ["/* generated by gen_fusion_policy.py from " + Path(flow).name + " and " + Path(cam).name + " (do not edit) */", "#ifndef FUSION_POLICY_H", "#define FUSION_POLICY_H", "#include <stdint.h>",
         f"static const uint8_t FUSION_TABLE[] = {{\n  {hexb}\n}};", f"#define FUSION_TABLE_LEN {len(blob)}", f"#define FUSION_N_NODES {len(names)}",
         "static const char *const FUSION_NODE_NAMES[] = { " + ", ".join(f'"{n}"' for n in names) + " };"]
for name, idx in img.fields.items(): lines.append(f"#define FREG_{name} {idx}")
lines += ["#define FUSION_A 0x81f0", "#define FUSION_B 0x6d40", f"#define CAM_OCC_MASK {occ:#x}   /* {[n for n in cnames if n in ('occupied', 'door', 'evidence')]} */", f"#define CAM_TAMPER_MASK {tam:#x}", "#endif"]
Path(__file__).parent.joinpath("main", "fusion_policy.h").write_text("\n".join(lines) + "\n")
print(f"fusion_policy.h: table {len(blob)} B, nodes {names}, camera nodes {cnames}, occ mask {occ:#x}, tamper mask {tam:#x}")
