#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Crystal Warden Supply Chain Labs LLC
"""Compile the relay's power policy to its .ppt image and emit main/hop_policy.h: the table bytes, the field
register map and the node names. The relay evaluates it once a second on its own counters.

    python gen_hop_policy.py [flow.md]
"""
import sys
from pathlib import Path
HW = Path(__file__).resolve().parent.parent; REPO = HW.parent
sys.path.insert(0, str(HW)); sys.path.insert(0, str(REPO))
import ppt_compile as pc
from prismpath.kernel.parser import parse_file
if len(sys.argv) < 2: sys.exit("usage: gen_hop_policy.py <flow.md>   (the authored flow lives with the deployment, not in this repository)")
flow = sys.argv[1]
g = parse_file(flow); img = pc.compile_flow(g, 25); blob = img.serialize(); names = [n for n, _ in img.nodes]
hexb = ",\n  ".join(", ".join(f"0x{b:02x}" for b in blob[i:i + 16]) for i in range(0, len(blob), 16))
lines = ["/* generated by gen_hop_policy.py from " + Path(flow).name + " (do not edit) */", "#ifndef HOP_POLICY_H", "#define HOP_POLICY_H", "#include <stdint.h>",
         f"static const uint8_t POLICY_TABLE[] = {{\n  {hexb}\n}};", f"#define POLICY_TABLE_LEN {len(blob)}", f"#define POLICY_N_NODES {len(names)}", f"#define POLICY_START {names.index(g.start)}",
         "static const char *const POLICY_NODE_NAMES[] = { " + ", ".join(f'"{n}"' for n in names) + " };"]
for name, idx in img.fields.items(): lines.append(f"#define REG_{name} {idx}")
lines.append("#endif")
Path(__file__).parent.joinpath("main", "hop_policy.h").write_text("\n".join(lines) + "\n")
print(f"hop_policy.h: table {len(blob)} B, {len(img.fields)} registers, nodes {names}, start {g.start}")
