#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Crystal Warden Supply Chain Labs LLC
"""Generate the spiral-mesh firmware data: the k=3 fusion flow's baked sidecar + the role map
(real board MACs) + deterministic per-role synthesis params. The per-channel quantizers DERIVE
from the signed flow's atoms — the thing #101's hand-coded bands were standing in for. The host
referee reproduces the synthesis and the derived layout, so every frame on the air is checkable."""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "adapters", "telemetry"))
sys.path.insert(0, os.path.join(HERE, "..", ".."))

import spiral as sp                      # noqa: E402
import spiral_pack as spk                # noqa: E402
from prismpath.parser import parse       # noqa: E402

FLOW = """---
name: mesh_fusion
start: decide
packing: spiral
---
## decide
-> alarm: when range_a < 200 and range_b < 200 and pot >= 600
-> intrude: when range_a < 200 and range_b < 200
-> watch: when range_a < 200 or range_b < 200
-> ok: else
## alarm
## intrude
## watch
## ok
"""
NODE = "decide"

# role -> (mac, field, synth lo, hi, period, phase); triangle sweep crossing the field's cut
ROLES = [
    ("58:2a:bd:76:6a:bc", "range_a", 100, 320, 20, 0),
    ("68:09:47:df:d5:90", "range_b", 120, 300, 26, 7),
    ("68:09:47:e0:38:00", "pot",     400, 800, 34, 13),
]


def synth(role, tick):
    _mac, _f, lo, hi, period, phase = ROLES[role]
    pos = (tick + phase) % period
    half = period // 2
    x = pos if pos <= half else period - pos
    return lo + (x * (hi - lo)) // half


def main():
    g = parse(FLOW)
    blob = spk.serialize_layouts(g, [NODE])
    L = sp.SpiralLayout(g, NODE)
    field_idx = {f: i for i, f in enumerate(L.fields)}

    with open(os.path.join(HERE, "main", "sidecar_blob.h"), "w") as f:
        f.write("// GENERATED by gen_spiral_mesh_data.py\n#pragma once\n#include <stdint.h>\n")
        f.write(f"static const uint8_t SIDECAR[{len(blob)}] = {{\n")
        for i in range(0, len(blob), 12):
            f.write("  " + ", ".join(f"0x{b:02x}" for b in blob[i:i + 12]) + ",\n")
        f.write("};\n")

    with open(os.path.join(HERE, "main", "roles.h"), "w") as f:
        f.write("// GENERATED by gen_spiral_mesh_data.py — role map + synthesis params\n")
        f.write("#pragma once\n#include <stdint.h>\n#define N_ROLES 3\n")
        f.write(f"// sidecar field order: {', '.join(L.fields)}\n")
        f.write("static const uint8_t ROLE_MAC[N_ROLES][6] = {\n")
        for mac, *_ in ROLES:
            f.write("  {" + ", ".join(f"0x{b}" for b in mac.split(":")) + "},\n")
        f.write("};\n")
        f.write("static const uint8_t ROLE_FIELD[N_ROLES] = {" +
                ", ".join(str(field_idx[r[1]]) for r in ROLES) + "};\n")
        f.write("static const int32_t ROLE_SYNTH[N_ROLES][4] = {  // lo, hi, period, phase\n")
        for _mac, _f, lo, hi, period, phase in ROLES:
            f.write(f"  {{{lo}, {hi}, {period}, {phase}}},\n")
        f.write("};\n")

    print(f"sidecar {len(blob)}B  fields={L.fields}  bands={len(L.routes)} size={L.size}")


if __name__ == "__main__":
    main()
