-- SPDX-License-Identifier: Apache-2.0
-- Copyright 2026 Crystal Warden Supply Chain Labs LLC
-- GENERATED by formal/gen_vectors.py from the frozen corpora and the reference quantizer. Do not edit.
-- predicates.json sha256 49e17b9ceb45b25fa47b8b2ac93c7c3b3a074c8ce843276eaf9a92894a0aba7b
-- decisions.json   sha256 6b68a08de7f57cdd11bee07bd256587094dc353b959d1195473c6880472479c8
-- spiral_fusion.json sha256 1d9dec55645adfe3a63ba7ee555fc45f2aae69d68c53542574876a96d844eaa4
-- counts: checked 35, cross kind comparison 13, non scalar or float constant 15, not Level M 943, referenced field missing or null 72, routes checked 90, shape not carried (non literal operand) 1, spiral probes checked 34, symbols checked against the reference 164
import FQ.Partition

namespace FQ.Vectors
open FQ

/-- A total reading from an association list; absent fields read as 0 (never referenced by the
checked conditions, the generator filters those cases out). -/
def readingOf (l : List (String × Value)) : Reading := fun f => (l.lookup f).getD (.int 0)

/-! ## predicates.json (version 2, 1079 cases): the Level M, well typed subset -/
#guard evalCond (readingOf [("x", .bool true)]) (Cond.cmp "x" .eq (.bool true)) == true  -- case 0: when x == True
#guard evalCond (readingOf [("x", .int (-5))]) (Cond.cmp "x" .ge (.int (-5))) == true  -- case 11: when x >= -5
#guard evalCond (readingOf [("x", .int (-6))]) (Cond.cmp "x" .ge (.int (-5))) == false  -- case 12: when x >= -5
#guard evalCond (readingOf [("x", .int (-2000))]) (Cond.cmp "x" .lt (.int (-1282))) == true  -- case 13: when x < -1282
#guard evalCond (readingOf [("x", .int 5)]) (Cond.cmp "x" .gt (.int (-1))) == true  -- case 14: when -1 < x
#guard evalCond (readingOf [("x", .int (-3))]) (Cond.cmp "x" .eq (.int (-3))) == true  -- case 15: when x == -3
#guard evalCond (readingOf [("x", .int 0)]) (Cond.cmp "x" .ne (.int (-3))) == true  -- case 16: when x != -3
#guard evalCond (readingOf [("x", .int (-1))]) (Cond.mem "x" [.int (-3), .int (-1), .int 2]) == true  -- case 18: when x in [-3, -1, 2]
#guard evalCond (readingOf [("x", .int 0)]) (Cond.mem "x" [.int (-3), .int (-1), .int 2]) == false  -- case 19: when x in [-3, -1, 2]
#guard evalCond (readingOf [("x", .int 3)]) (Cond.and (Cond.cmp "x" .gt (.int 1)) (Cond.cmp "x" .lt (.int 5))) == true  -- case 28: when 1 < x < 5
#guard evalCond (readingOf [("x", .int 7)]) (Cond.and (Cond.cmp "x" .gt (.int 1)) (Cond.cmp "x" .lt (.int 5))) == false  -- case 29: when 1 < x < 5
#guard evalCond (readingOf [("a", .str "watch")]) (Cond.mem "a" [.str "contain", .str "watch"]) == true  -- case 34: when a in ["contain", "watch"]
#guard evalCond (readingOf [("a", .str "contain")]) (Cond.mem "a" [.str "contain", .str "watch"]) == true  -- case 35: when a in ("contain", "watch")
#guard evalCond (readingOf [("x", .int 1)]) (Cond.mem "x" []) == false  -- case 38: when x in ()
#guard evalCond (readingOf [("s", .str "")]) (Cond.truthy "s") == false  -- case 43: when s
#guard evalCond (readingOf [("ok", .bool true), ("s", .str "x")]) (Cond.and (Cond.truthy "s") (Cond.truthy "ok")) == true  -- case 44: when s and ok
#guard evalCond (readingOf [("match", .int 1)]) (Cond.cmp "match" .eq (.int 1)) == true  -- case 47: when match == 1
#guard evalCond (readingOf [("type", .str "a")]) (Cond.cmp "type" .eq (.str "a")) == true  -- case 48: when type == 'a'
#guard evalCond (readingOf [("x", .int 1)]) (Cond.truthy "x") == true  -- case 49: when ((((((((((x))))))))))
#guard evalCond (readingOf [("a", .int 0), ("b", .int 1), ("c", .int 1)]) (Cond.and (Cond.or (Cond.truthy "a") (Cond.truthy "b")) (Cond.truthy "c")) == true  -- case 50: when (a or b) and c
#guard evalCond (readingOf [("n", .int 16)]) (Cond.cmp "n" .eq (.int 16)) == true  -- case 53: when n == 0x10
#guard evalCond (readingOf [("n", .int 15)]) (Cond.cmp "n" .eq (.int 15)) == true  -- case 54: when n == 0o17
#guard evalCond (readingOf [("n", .int 5)]) (Cond.cmp "n" .eq (.int 5)) == true  -- case 55: when n == 0b101
#guard evalCond (readingOf [("n", .int 1000)]) (Cond.cmp "n" .eq (.int 1000)) == true  -- case 56: when n == 1_000
#guard evalCond (readingOf [("x", .str "A")]) (Cond.cmp "x" .eq (.str "A")) == true  -- case 58: when x == "\x41"
#guard evalCond (readingOf [("x", .str "A")]) (Cond.cmp "x" .eq (.str "A")) == true  -- case 59: when x == "\u0041"
#guard evalCond (readingOf [("x", .str "\\n")]) (Cond.cmp "x" .eq (.str "\\n")) == true  -- case 60: when x == r'\n'
#guard evalCond (readingOf [("x", .str "a\\qb")]) (Cond.cmp "x" .eq (.str "a\\qb")) == true  -- case 61: when x == "a\qb"
#guard evalCond (readingOf [("x", .int 5)]) (Cond.cmp "x" .gt (.int (-1))) == true  -- case 69: when -1 < x
#guard evalCond (readingOf []) Cond.tt == true  -- case 72: always
#guard evalCond (readingOf []) Cond.tt == true  -- case 73: else
#guard evalCond (readingOf [("items", .int 2)]) (Cond.cmp "items" .ge (.int 10)) == false  -- case 99: when 10 <= items
#guard evalCond (readingOf [("score", .int 1)]) (Cond.not (Cond.mem "score" [])) == true  -- case 595: when not score in []
#guard evalCond (readingOf [("items", .int 10)]) (Cond.cmp "items" .lt (.int 1000)) == true  -- case 896: when 1000 > items
#guard evalCond (readingOf [("action", .str "café")]) (Cond.not (Cond.cmp "action" .eq (.str "error happened"))) == true  -- case 948: when not action == 'error happened'

/-! ## decisions.json (version 2, 7 flows): routes and canonical symbols against the reference quantizer -/
def incident_severity_all : Policy String := [⟨(Cond.truthy "data_at_risk"), "sev1_page"⟩, ⟨(Cond.and (Cond.truthy "user_facing") (Cond.cmp "error_rate" .ge (.int 25))), "sev1_page"⟩, ⟨(Cond.and (Cond.truthy "user_facing") (Cond.cmp "error_rate" .ge (.int 5))), "sev2_oncall"⟩, ⟨(Cond.cmp "error_rate" .ge (.int 1)), "sev3_ticket"⟩, ⟨Cond.tt, "watch"⟩]
def incident_severity_assess : Policy String := [⟨(Cond.truthy "data_at_risk"), "sev1_page"⟩, ⟨(Cond.and (Cond.truthy "user_facing") (Cond.cmp "error_rate" .ge (.int 25))), "sev1_page"⟩, ⟨(Cond.and (Cond.truthy "user_facing") (Cond.cmp "error_rate" .ge (.int 5))), "sev2_oncall"⟩, ⟨(Cond.cmp "error_rate" .ge (.int 1)), "sev3_ticket"⟩, ⟨Cond.tt, "watch"⟩]
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool false), ("error_rate", .int 0), ("user_facing", .bool false)]) == some "watch"  -- incident_severity reading 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 0), ("user_facing", .bool false)])).lookup "data_at_risk" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 0), ("user_facing", .bool false)])).lookup "error_rate" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 0), ("user_facing", .bool false)])).lookup "user_facing" == some 0
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool false), ("error_rate", .int 0), ("user_facing", .bool true)]) == some "watch"  -- incident_severity reading 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 0), ("user_facing", .bool true)])).lookup "data_at_risk" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 0), ("user_facing", .bool true)])).lookup "error_rate" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 0), ("user_facing", .bool true)])).lookup "user_facing" == some 1
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool false), ("error_rate", .int 1), ("user_facing", .bool false)]) == some "sev3_ticket"  -- incident_severity reading 2
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 1), ("user_facing", .bool false)])).lookup "data_at_risk" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 1), ("user_facing", .bool false)])).lookup "error_rate" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 1), ("user_facing", .bool false)])).lookup "user_facing" == some 0
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool false), ("error_rate", .int 1), ("user_facing", .bool true)]) == some "sev3_ticket"  -- incident_severity reading 3
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 1), ("user_facing", .bool true)])).lookup "data_at_risk" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 1), ("user_facing", .bool true)])).lookup "error_rate" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 1), ("user_facing", .bool true)])).lookup "user_facing" == some 1
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool false), ("error_rate", .int 4), ("user_facing", .bool false)]) == some "sev3_ticket"  -- incident_severity reading 4
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 4), ("user_facing", .bool false)])).lookup "data_at_risk" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 4), ("user_facing", .bool false)])).lookup "error_rate" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 4), ("user_facing", .bool false)])).lookup "user_facing" == some 0
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool false), ("error_rate", .int 4), ("user_facing", .bool true)]) == some "sev3_ticket"  -- incident_severity reading 5
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 4), ("user_facing", .bool true)])).lookup "data_at_risk" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 4), ("user_facing", .bool true)])).lookup "error_rate" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 4), ("user_facing", .bool true)])).lookup "user_facing" == some 1
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool false), ("error_rate", .int 5), ("user_facing", .bool false)]) == some "sev3_ticket"  -- incident_severity reading 6
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 5), ("user_facing", .bool false)])).lookup "data_at_risk" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 5), ("user_facing", .bool false)])).lookup "error_rate" == some 2
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 5), ("user_facing", .bool false)])).lookup "user_facing" == some 0
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool false), ("error_rate", .int 5), ("user_facing", .bool true)]) == some "sev2_oncall"  -- incident_severity reading 7
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 5), ("user_facing", .bool true)])).lookup "data_at_risk" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 5), ("user_facing", .bool true)])).lookup "error_rate" == some 2
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 5), ("user_facing", .bool true)])).lookup "user_facing" == some 1
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool false), ("error_rate", .int 24), ("user_facing", .bool false)]) == some "sev3_ticket"  -- incident_severity reading 8
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 24), ("user_facing", .bool false)])).lookup "data_at_risk" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 24), ("user_facing", .bool false)])).lookup "error_rate" == some 2
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 24), ("user_facing", .bool false)])).lookup "user_facing" == some 0
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool false), ("error_rate", .int 24), ("user_facing", .bool true)]) == some "sev2_oncall"  -- incident_severity reading 9
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 24), ("user_facing", .bool true)])).lookup "data_at_risk" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 24), ("user_facing", .bool true)])).lookup "error_rate" == some 2
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 24), ("user_facing", .bool true)])).lookup "user_facing" == some 1
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool false), ("error_rate", .int 25), ("user_facing", .bool false)]) == some "sev3_ticket"  -- incident_severity reading 10
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 25), ("user_facing", .bool false)])).lookup "data_at_risk" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 25), ("user_facing", .bool false)])).lookup "error_rate" == some 3
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 25), ("user_facing", .bool false)])).lookup "user_facing" == some 0
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool false), ("error_rate", .int 25), ("user_facing", .bool true)]) == some "sev1_page"  -- incident_severity reading 11
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 25), ("user_facing", .bool true)])).lookup "data_at_risk" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 25), ("user_facing", .bool true)])).lookup "error_rate" == some 3
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 25), ("user_facing", .bool true)])).lookup "user_facing" == some 1
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool true), ("error_rate", .int 0), ("user_facing", .bool false)]) == some "sev1_page"  -- incident_severity reading 12
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 0), ("user_facing", .bool false)])).lookup "data_at_risk" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 0), ("user_facing", .bool false)])).lookup "error_rate" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 0), ("user_facing", .bool false)])).lookup "user_facing" == some 0
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool true), ("error_rate", .int 0), ("user_facing", .bool true)]) == some "sev1_page"  -- incident_severity reading 13
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 0), ("user_facing", .bool true)])).lookup "data_at_risk" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 0), ("user_facing", .bool true)])).lookup "error_rate" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 0), ("user_facing", .bool true)])).lookup "user_facing" == some 1
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool true), ("error_rate", .int 1), ("user_facing", .bool false)]) == some "sev1_page"  -- incident_severity reading 14
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 1), ("user_facing", .bool false)])).lookup "data_at_risk" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 1), ("user_facing", .bool false)])).lookup "error_rate" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 1), ("user_facing", .bool false)])).lookup "user_facing" == some 0
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool true), ("error_rate", .int 1), ("user_facing", .bool true)]) == some "sev1_page"  -- incident_severity reading 15
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 1), ("user_facing", .bool true)])).lookup "data_at_risk" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 1), ("user_facing", .bool true)])).lookup "error_rate" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 1), ("user_facing", .bool true)])).lookup "user_facing" == some 1
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool true), ("error_rate", .int 4), ("user_facing", .bool false)]) == some "sev1_page"  -- incident_severity reading 16
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 4), ("user_facing", .bool false)])).lookup "data_at_risk" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 4), ("user_facing", .bool false)])).lookup "error_rate" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 4), ("user_facing", .bool false)])).lookup "user_facing" == some 0
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool true), ("error_rate", .int 4), ("user_facing", .bool true)]) == some "sev1_page"  -- incident_severity reading 17
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 4), ("user_facing", .bool true)])).lookup "data_at_risk" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 4), ("user_facing", .bool true)])).lookup "error_rate" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 4), ("user_facing", .bool true)])).lookup "user_facing" == some 1
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool true), ("error_rate", .int 5), ("user_facing", .bool false)]) == some "sev1_page"  -- incident_severity reading 18
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 5), ("user_facing", .bool false)])).lookup "data_at_risk" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 5), ("user_facing", .bool false)])).lookup "error_rate" == some 2
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 5), ("user_facing", .bool false)])).lookup "user_facing" == some 0
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool true), ("error_rate", .int 5), ("user_facing", .bool true)]) == some "sev1_page"  -- incident_severity reading 19
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 5), ("user_facing", .bool true)])).lookup "data_at_risk" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 5), ("user_facing", .bool true)])).lookup "error_rate" == some 2
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 5), ("user_facing", .bool true)])).lookup "user_facing" == some 1
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool true), ("error_rate", .int 24), ("user_facing", .bool false)]) == some "sev1_page"  -- incident_severity reading 20
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 24), ("user_facing", .bool false)])).lookup "data_at_risk" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 24), ("user_facing", .bool false)])).lookup "error_rate" == some 2
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 24), ("user_facing", .bool false)])).lookup "user_facing" == some 0
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool true), ("error_rate", .int 24), ("user_facing", .bool true)]) == some "sev1_page"  -- incident_severity reading 21
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 24), ("user_facing", .bool true)])).lookup "data_at_risk" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 24), ("user_facing", .bool true)])).lookup "error_rate" == some 2
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 24), ("user_facing", .bool true)])).lookup "user_facing" == some 1
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool true), ("error_rate", .int 25), ("user_facing", .bool false)]) == some "sev1_page"  -- incident_severity reading 22
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 25), ("user_facing", .bool false)])).lookup "data_at_risk" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 25), ("user_facing", .bool false)])).lookup "error_rate" == some 3
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 25), ("user_facing", .bool false)])).lookup "user_facing" == some 0
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool true), ("error_rate", .int 25), ("user_facing", .bool true)]) == some "sev1_page"  -- incident_severity reading 23
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 25), ("user_facing", .bool true)])).lookup "data_at_risk" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 25), ("user_facing", .bool true)])).lookup "error_rate" == some 3
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 25), ("user_facing", .bool true)])).lookup "user_facing" == some 1
def cat_all : Policy String := [⟨(Cond.cmp "kind" .eq (.str "urgent")), "urgent"⟩, ⟨(Cond.mem "kind" [.str "nightly", .str "weekly"]), "batch"⟩, ⟨(Cond.cmp "status" .ne (.str "ok")), "blocked"⟩, ⟨Cond.tt, "normal"⟩]
def cat_classify : Policy String := [⟨(Cond.cmp "kind" .eq (.str "urgent")), "urgent"⟩, ⟨(Cond.mem "kind" [.str "nightly", .str "weekly"]), "batch"⟩, ⟨(Cond.cmp "status" .ne (.str "ok")), "blocked"⟩, ⟨Cond.tt, "normal"⟩]
#guard route cat_classify (readingOf [("kind", .str "urgent"), ("status", .str "ok")]) == some "urgent"  -- cat reading 0
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "urgent"), ("status", .str "ok")])).lookup "kind" == some 0
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "urgent"), ("status", .str "ok")])).lookup "status" == some 0
#guard route cat_classify (readingOf [("kind", .str "urgent"), ("status", .str "__unlisted__")]) == some "urgent"  -- cat reading 1
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "urgent"), ("status", .str "__unlisted__")])).lookup "kind" == some 0
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "urgent"), ("status", .str "__unlisted__")])).lookup "status" == some 1
#guard route cat_classify (readingOf [("kind", .str "nightly"), ("status", .str "ok")]) == some "batch"  -- cat reading 2
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "nightly"), ("status", .str "ok")])).lookup "kind" == some 1
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "nightly"), ("status", .str "ok")])).lookup "status" == some 0
#guard route cat_classify (readingOf [("kind", .str "nightly"), ("status", .str "__unlisted__")]) == some "batch"  -- cat reading 3
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "nightly"), ("status", .str "__unlisted__")])).lookup "kind" == some 1
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "nightly"), ("status", .str "__unlisted__")])).lookup "status" == some 1
#guard route cat_classify (readingOf [("kind", .str "weekly"), ("status", .str "ok")]) == some "batch"  -- cat reading 4
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "weekly"), ("status", .str "ok")])).lookup "kind" == some 2
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "weekly"), ("status", .str "ok")])).lookup "status" == some 0
#guard route cat_classify (readingOf [("kind", .str "weekly"), ("status", .str "__unlisted__")]) == some "batch"  -- cat reading 5
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "weekly"), ("status", .str "__unlisted__")])).lookup "kind" == some 2
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "weekly"), ("status", .str "__unlisted__")])).lookup "status" == some 1
#guard route cat_classify (readingOf [("kind", .str "__unlisted__"), ("status", .str "ok")]) == some "normal"  -- cat reading 6
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "__unlisted__"), ("status", .str "ok")])).lookup "kind" == some 3
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "__unlisted__"), ("status", .str "ok")])).lookup "status" == some 0
#guard route cat_classify (readingOf [("kind", .str "__unlisted__"), ("status", .str "__unlisted__")]) == some "blocked"  -- cat reading 7
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "__unlisted__"), ("status", .str "__unlisted__")])).lookup "kind" == some 3
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "__unlisted__"), ("status", .str "__unlisted__")])).lookup "status" == some 1
def numeq_all : Policy String := [⟨(Cond.cmp "x" .eq (.int 5)), "exact"⟩, ⟨(Cond.cmp "x" .ge (.int 10)), "high"⟩, ⟨Cond.tt, "low"⟩]
def numeq_classify : Policy String := [⟨(Cond.cmp "x" .eq (.int 5)), "exact"⟩, ⟨(Cond.cmp "x" .ge (.int 10)), "high"⟩, ⟨Cond.tt, "low"⟩]
#guard route numeq_classify (readingOf [("x", .int 4)]) == some "low"  -- numeq reading 0
#guard (quantize (buildPartitions numeq_all) (readingOf [("x", .int 4)])).lookup "x" == some 0
#guard route numeq_classify (readingOf [("x", .int 5)]) == some "exact"  -- numeq reading 1
#guard (quantize (buildPartitions numeq_all) (readingOf [("x", .int 5)])).lookup "x" == some 1
#guard route numeq_classify (readingOf [("x", .int 6)]) == some "low"  -- numeq reading 2
#guard (quantize (buildPartitions numeq_all) (readingOf [("x", .int 6)])).lookup "x" == some 2
#guard route numeq_classify (readingOf [("x", .int 9)]) == some "low"  -- numeq reading 3
#guard (quantize (buildPartitions numeq_all) (readingOf [("x", .int 9)])).lookup "x" == some 2
#guard route numeq_classify (readingOf [("x", .int 10)]) == some "high"  -- numeq reading 4
#guard (quantize (buildPartitions numeq_all) (readingOf [("x", .int 10)])).lookup "x" == some 3
def pipeline_all : Policy String := [⟨(Cond.cmp "size" .gt (.int 1000)), "reject"⟩, ⟨Cond.tt, "triage"⟩, ⟨(Cond.cmp "priority" .ge (.int 8)), "urgent"⟩, ⟨(Cond.mem "kind" [.str "nightly", .str "weekly"]), "batch"⟩, ⟨Cond.tt, "normal"⟩]
def pipeline_intake : Policy String := [⟨(Cond.cmp "size" .gt (.int 1000)), "reject"⟩, ⟨Cond.tt, "triage"⟩]
def pipeline_triage : Policy String := [⟨(Cond.cmp "priority" .ge (.int 8)), "urgent"⟩, ⟨(Cond.mem "kind" [.str "nightly", .str "weekly"]), "batch"⟩, ⟨Cond.tt, "normal"⟩]
#guard route pipeline_intake (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 999)]) == some "triage"  -- pipeline reading 0
#guard route pipeline_triage (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 999)]) == some "batch"  -- pipeline reading 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 999)])).lookup "kind" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 999)])).lookup "priority" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 999)])).lookup "size" == some 0
#guard route pipeline_intake (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 1000)]) == some "triage"  -- pipeline reading 1
#guard route pipeline_triage (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 1000)]) == some "batch"  -- pipeline reading 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 1000)])).lookup "kind" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 1000)])).lookup "priority" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 1000)])).lookup "size" == some 0
#guard route pipeline_intake (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 1001)]) == some "reject"  -- pipeline reading 2
#guard route pipeline_triage (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 1001)]) == some "batch"  -- pipeline reading 2
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 1001)])).lookup "kind" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 1001)])).lookup "priority" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 1001)])).lookup "size" == some 1
#guard route pipeline_intake (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 999)]) == some "triage"  -- pipeline reading 3
#guard route pipeline_triage (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 999)]) == some "urgent"  -- pipeline reading 3
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 999)])).lookup "kind" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 999)])).lookup "priority" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 999)])).lookup "size" == some 0
#guard route pipeline_intake (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 1000)]) == some "triage"  -- pipeline reading 4
#guard route pipeline_triage (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 1000)]) == some "urgent"  -- pipeline reading 4
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 1000)])).lookup "kind" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 1000)])).lookup "priority" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 1000)])).lookup "size" == some 0
#guard route pipeline_intake (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 1001)]) == some "reject"  -- pipeline reading 5
#guard route pipeline_triage (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 1001)]) == some "urgent"  -- pipeline reading 5
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 1001)])).lookup "kind" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 1001)])).lookup "priority" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 1001)])).lookup "size" == some 1
#guard route pipeline_intake (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 999)]) == some "triage"  -- pipeline reading 6
#guard route pipeline_triage (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 999)]) == some "batch"  -- pipeline reading 6
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 999)])).lookup "kind" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 999)])).lookup "priority" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 999)])).lookup "size" == some 0
#guard route pipeline_intake (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 1000)]) == some "triage"  -- pipeline reading 7
#guard route pipeline_triage (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 1000)]) == some "batch"  -- pipeline reading 7
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 1000)])).lookup "kind" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 1000)])).lookup "priority" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 1000)])).lookup "size" == some 0
#guard route pipeline_intake (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 1001)]) == some "reject"  -- pipeline reading 8
#guard route pipeline_triage (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 1001)]) == some "batch"  -- pipeline reading 8
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 1001)])).lookup "kind" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 1001)])).lookup "priority" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 1001)])).lookup "size" == some 1
#guard route pipeline_intake (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 999)]) == some "triage"  -- pipeline reading 9
#guard route pipeline_triage (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 999)]) == some "urgent"  -- pipeline reading 9
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 999)])).lookup "kind" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 999)])).lookup "priority" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 999)])).lookup "size" == some 0
#guard route pipeline_intake (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 1000)]) == some "triage"  -- pipeline reading 10
#guard route pipeline_triage (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 1000)]) == some "urgent"  -- pipeline reading 10
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 1000)])).lookup "kind" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 1000)])).lookup "priority" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 1000)])).lookup "size" == some 0
#guard route pipeline_intake (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 1001)]) == some "reject"  -- pipeline reading 11
#guard route pipeline_triage (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 1001)]) == some "urgent"  -- pipeline reading 11
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 1001)])).lookup "kind" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 1001)])).lookup "priority" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 1001)])).lookup "size" == some 1
#guard route pipeline_intake (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 999)]) == some "triage"  -- pipeline reading 12
#guard route pipeline_triage (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 999)]) == some "normal"  -- pipeline reading 12
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 999)])).lookup "kind" == some 2
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 999)])).lookup "priority" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 999)])).lookup "size" == some 0
#guard route pipeline_intake (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 1000)]) == some "triage"  -- pipeline reading 13
#guard route pipeline_triage (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 1000)]) == some "normal"  -- pipeline reading 13
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 1000)])).lookup "kind" == some 2
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 1000)])).lookup "priority" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 1000)])).lookup "size" == some 0
#guard route pipeline_intake (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 1001)]) == some "reject"  -- pipeline reading 14
#guard route pipeline_triage (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 1001)]) == some "normal"  -- pipeline reading 14
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 1001)])).lookup "kind" == some 2
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 1001)])).lookup "priority" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 1001)])).lookup "size" == some 1
#guard route pipeline_intake (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 999)]) == some "triage"  -- pipeline reading 15
#guard route pipeline_triage (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 999)]) == some "urgent"  -- pipeline reading 15
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 999)])).lookup "kind" == some 2
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 999)])).lookup "priority" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 999)])).lookup "size" == some 0
#guard route pipeline_intake (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 1000)]) == some "triage"  -- pipeline reading 16
#guard route pipeline_triage (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 1000)]) == some "urgent"  -- pipeline reading 16
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 1000)])).lookup "kind" == some 2
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 1000)])).lookup "priority" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 1000)])).lookup "size" == some 0
#guard route pipeline_intake (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 1001)]) == some "reject"  -- pipeline reading 17
#guard route pipeline_triage (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 1001)]) == some "urgent"  -- pipeline reading 17
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 1001)])).lookup "kind" == some 2
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 1001)])).lookup "priority" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 1001)])).lookup "size" == some 1
def numin_all : Policy String := [⟨(Cond.mem "x" [.int 3, .int 5]), "listed"⟩, ⟨(Cond.nmem "x" [.int 7, .int 9]), "excluded"⟩, ⟨Cond.tt, "rest"⟩]
def numin_classify : Policy String := [⟨(Cond.mem "x" [.int 3, .int 5]), "listed"⟩, ⟨(Cond.nmem "x" [.int 7, .int 9]), "excluded"⟩, ⟨Cond.tt, "rest"⟩]
#guard route numin_classify (readingOf [("x", .int 2)]) == some "excluded"  -- numin reading 0
#guard (quantize (buildPartitions numin_all) (readingOf [("x", .int 2)])).lookup "x" == some 0
#guard route numin_classify (readingOf [("x", .int 3)]) == some "listed"  -- numin reading 1
#guard (quantize (buildPartitions numin_all) (readingOf [("x", .int 3)])).lookup "x" == some 1
#guard route numin_classify (readingOf [("x", .int 4)]) == some "excluded"  -- numin reading 2
#guard (quantize (buildPartitions numin_all) (readingOf [("x", .int 4)])).lookup "x" == some 2
#guard route numin_classify (readingOf [("x", .int 5)]) == some "listed"  -- numin reading 3
#guard (quantize (buildPartitions numin_all) (readingOf [("x", .int 5)])).lookup "x" == some 3
#guard route numin_classify (readingOf [("x", .int 6)]) == some "excluded"  -- numin reading 4
#guard (quantize (buildPartitions numin_all) (readingOf [("x", .int 6)])).lookup "x" == some 4
#guard route numin_classify (readingOf [("x", .int 7)]) == some "rest"  -- numin reading 5
#guard (quantize (buildPartitions numin_all) (readingOf [("x", .int 7)])).lookup "x" == some 5
#guard route numin_classify (readingOf [("x", .int 8)]) == some "excluded"  -- numin reading 6
#guard (quantize (buildPartitions numin_all) (readingOf [("x", .int 8)])).lookup "x" == some 6
#guard route numin_classify (readingOf [("x", .int 9)]) == some "rest"  -- numin reading 7
#guard (quantize (buildPartitions numin_all) (readingOf [("x", .int 9)])).lookup "x" == some 7
#guard route numin_classify (readingOf [("x", .int 10)]) == some "excluded"  -- numin reading 8
#guard (quantize (buildPartitions numin_all) (readingOf [("x", .int 10)])).lookup "x" == some 8
def truthynum_all : Policy String := [⟨(Cond.cmp "x" .ge (.int 5)), "high"⟩, ⟨(Cond.truthy "x"), "nonzero"⟩, ⟨Cond.tt, "zero"⟩]
def truthynum_classify : Policy String := [⟨(Cond.cmp "x" .ge (.int 5)), "high"⟩, ⟨(Cond.truthy "x"), "nonzero"⟩, ⟨Cond.tt, "zero"⟩]
#guard route truthynum_classify (readingOf [("x", .int (-1))]) == some "nonzero"  -- truthynum reading 0
#guard (quantize (buildPartitions truthynum_all) (readingOf [("x", .int (-1))])).lookup "x" == some 0
#guard route truthynum_classify (readingOf [("x", .int 0)]) == some "zero"  -- truthynum reading 1
#guard (quantize (buildPartitions truthynum_all) (readingOf [("x", .int 0)])).lookup "x" == some 1
#guard route truthynum_classify (readingOf [("x", .int 1)]) == some "nonzero"  -- truthynum reading 2
#guard (quantize (buildPartitions truthynum_all) (readingOf [("x", .int 1)])).lookup "x" == some 2
#guard route truthynum_classify (readingOf [("x", .int 4)]) == some "nonzero"  -- truthynum reading 3
#guard (quantize (buildPartitions truthynum_all) (readingOf [("x", .int 4)])).lookup "x" == some 2
#guard route truthynum_classify (readingOf [("x", .int 5)]) == some "high"  -- truthynum reading 4
#guard (quantize (buildPartitions truthynum_all) (readingOf [("x", .int 5)])).lookup "x" == some 3
def strtruthy_all : Policy String := [⟨(Cond.cmp "name" .eq (.str "root")), "root"⟩, ⟨(Cond.truthy "name"), "named"⟩, ⟨Cond.tt, "anonymous"⟩]
def strtruthy_classify : Policy String := [⟨(Cond.cmp "name" .eq (.str "root")), "root"⟩, ⟨(Cond.truthy "name"), "named"⟩, ⟨Cond.tt, "anonymous"⟩]
#guard route strtruthy_classify (readingOf [("name", .str "root")]) == some "root"  -- strtruthy reading 0
#guard (quantize (buildPartitions strtruthy_all) (readingOf [("name", .str "root")])).lookup "name" == some 0
#guard route strtruthy_classify (readingOf [("name", .str "")]) == some "anonymous"  -- strtruthy reading 1
#guard (quantize (buildPartitions strtruthy_all) (readingOf [("name", .str "")])).lookup "name" == some 1
#guard route strtruthy_classify (readingOf [("name", .str "__unlisted__")]) == some "named"  -- strtruthy reading 2
#guard (quantize (buildPartitions strtruthy_all) (readingOf [("name", .str "__unlisted__")])).lookup "name" == some 2

/-! ## spiral_fusion.json (34 probes at node correlate) -/
def fusion_correlate : Policy String := [⟨(Cond.and (Cond.cmp "stability" .eq (.str "shaken")) (Cond.cmp "rule_level" .ge (.int 12))), "coincident_critical"⟩, ⟨(Cond.and (Cond.cmp "stability" .eq (.str "shaken")) (Cond.cmp "soc_action" .eq (.str "contain"))), "coincident_critical"⟩, ⟨(Cond.and (Cond.cmp "dev_mg" .ge (.int 2500)) (Cond.cmp "soc_action" .eq (.str "contain"))), "coincident_critical"⟩, ⟨(Cond.and (Cond.cmp "dev_mg" .ge (.int 150)) (Cond.cmp "rule_level" .ge (.int 12))), "coincident_critical"⟩, ⟨(Cond.or (Cond.cmp "stability" .eq (.str "shaken")) (Cond.cmp "dev_mg" .ge (.int 2500))), "physical_escalation"⟩, ⟨(Cond.or (Cond.cmp "soc_action" .eq (.str "contain")) (Cond.cmp "rule_level" .ge (.int 12))), "cyber_containment"⟩, ⟨(Cond.and (Cond.cmp "stability" .eq (.str "moving")) (Cond.cmp "rule_level" .ge (.int 7))), "tandem_watch"⟩, ⟨(Cond.and (Cond.cmp "dev_mg" .ge (.int 500)) (Cond.cmp "soc_action" .eq (.str "watch"))), "tandem_watch"⟩, ⟨(Cond.or (Cond.cmp "soc_action" .eq (.str "watch")) (Cond.cmp "rule_level" .ge (.int 7))), "cyber_watch"⟩, ⟨(Cond.or (Cond.cmp "stability" .eq (.str "moving")) (Cond.cmp "dev_mg" .ge (.int 500))), "physical_watch"⟩, ⟨Cond.tt, "all_quiet"⟩]
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "all_quiet"  -- probe 0
#guard route fusion_correlate (readingOf [("dev_mg", .int 149), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "all_quiet"  -- probe 1
#guard route fusion_correlate (readingOf [("dev_mg", .int 150), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "all_quiet"  -- probe 2
#guard route fusion_correlate (readingOf [("dev_mg", .int 151), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "all_quiet"  -- probe 3
#guard route fusion_correlate (readingOf [("dev_mg", .int 499), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "all_quiet"  -- probe 4
#guard route fusion_correlate (readingOf [("dev_mg", .int 500), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "physical_watch"  -- probe 5
#guard route fusion_correlate (readingOf [("dev_mg", .int 501), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "physical_watch"  -- probe 6
#guard route fusion_correlate (readingOf [("dev_mg", .int 2499), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "physical_watch"  -- probe 7
#guard route fusion_correlate (readingOf [("dev_mg", .int 2500), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "physical_escalation"  -- probe 8
#guard route fusion_correlate (readingOf [("dev_mg", .int 2501), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "physical_escalation"  -- probe 9
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 6), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "all_quiet"  -- probe 10
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 7), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "cyber_watch"  -- probe 11
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 8), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "cyber_watch"  -- probe 12
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 11), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "cyber_watch"  -- probe 13
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 12), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "cyber_containment"  -- probe 14
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 13), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "cyber_containment"  -- probe 15
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 0), ("soc_action", .str "contain"), ("stability", .str "still")]) == some "cyber_containment"  -- probe 16
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 0), ("soc_action", .str "watch"), ("stability", .str "still")]) == some "cyber_watch"  -- probe 17
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 0), ("soc_action", .str "none"), ("stability", .str "still")]) == some "all_quiet"  -- probe 18
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "shaken")]) == some "physical_escalation"  -- probe 19
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "moving")]) == some "physical_watch"  -- probe 20
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "On Table")]) == some "all_quiet"  -- probe 21
#guard route fusion_correlate (readingOf [("dev_mg", .int 3000), ("rule_level", .int 13), ("soc_action", .str "contain"), ("stability", .str "shaken")]) == some "coincident_critical"  -- probe 22
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 3), ("soc_action", .str "contain"), ("stability", .str "shaken")]) == some "coincident_critical"  -- probe 23
#guard route fusion_correlate (readingOf [("dev_mg", .int 3000), ("rule_level", .int 3), ("soc_action", .str "contain"), ("stability", .str "still")]) == some "coincident_critical"  -- probe 24
#guard route fusion_correlate (readingOf [("dev_mg", .int 200), ("rule_level", .int 12), ("soc_action", .str "watch"), ("stability", .str "still")]) == some "coincident_critical"  -- probe 25
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 12), ("soc_action", .str "contain"), ("stability", .str "still")]) == some "cyber_containment"  -- probe 26
#guard route fusion_correlate (readingOf [("dev_mg", .int 149), ("rule_level", .int 12), ("soc_action", .str "contain"), ("stability", .str "still")]) == some "cyber_containment"  -- probe 27
#guard route fusion_correlate (readingOf [("dev_mg", .int 2600), ("rule_level", .int 5), ("soc_action", .str "ignore"), ("stability", .str "shaken")]) == some "physical_escalation"  -- probe 28
#guard route fusion_correlate (readingOf [("dev_mg", .int 2500), ("rule_level", .int 3), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "physical_escalation"  -- probe 29
#guard route fusion_correlate (readingOf [("dev_mg", .int 600), ("rule_level", .int 8), ("soc_action", .str "watch"), ("stability", .str "moving")]) == some "tandem_watch"  -- probe 30
#guard route fusion_correlate (readingOf [("dev_mg", .int 600), ("rule_level", .int 3), ("soc_action", .str "watch"), ("stability", .str "still")]) == some "tandem_watch"  -- probe 31
#guard route fusion_correlate (readingOf [("dev_mg", .int 100), ("rule_level", .int 3), ("soc_action", .str "ignore"), ("stability", .str "moving")]) == some "physical_watch"  -- probe 32
#guard route fusion_correlate (readingOf [("dev_mg", .int 400), ("rule_level", .int 3), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "all_quiet"  -- probe 33

end FQ.Vectors
