-- SPDX-License-Identifier: Apache-2.0
-- Copyright 2026 Crystal Warden Supply Chain Labs LLC
-- GENERATED by formal/gen_vectors.py from the frozen corpora and the reference quantizer. Do not edit.
-- predicates.json sha256 49e17b9ceb45b25fa47b8b2ac93c7c3b3a074c8ce843276eaf9a92894a0aba7b
-- decisions.json   sha256 6b68a08de7f57cdd11bee07bd256587094dc353b959d1195473c6880472479c8
-- spiral_fusion.json sha256 1d9dec55645adfe3a63ba7ee555fc45f2aae69d68c53542574876a96d844eaa4
-- counts: checked 35, cross kind comparison 13, non scalar or float constant 15, not Level M 943, referenced field missing or null 72, routes checked 90, shape not carried (non literal operand) 1, spiral probes checked 34, symbols checked against the reference 164, zeckendorf codes checked against the reference 300
import FQ.Partition
import FQ.Zeckendorf

namespace FQ.Vectors
open FQ

/-- A total reading from an association list; absent fields read as 0 (never referenced by the
checked conditions, the generator filters those cases out). -/
def readingOf (l : List (String × Value)) : Reading := fun f => (l.lookup f).getD (.int 0)

/-! ## predicates.json (version 2, 1079 cases): the Level M, well typed subset -/
#guard evalCond (readingOf [("x", .bool true)]) (Cond.cmp "x" .eq (.bool true)) == true  -- case 0: when x == True
#guard evalCond (readingOf [("x", .int (-5))]) (Cond.cmp "x" .ge (.int (-5))) == true  -- case 11: when x >= -5
#guard evalCond (readingOf [("x", .int (-6))]) (Cond.cmp "x" .ge (.int (-5))) == false  -- case 12: when x >= -5
#guard evalCond (readingOf [("x", .int (-2000))]) (Cond.cmp "x" .lt (.int (-1282))) == true  -- case 13: when x < -1282
#guard evalCond (readingOf [("x", .int 5)]) (Cond.cmp "x" .gt (.int (-1))) == true  -- case 14: when -1 < x
#guard evalCond (readingOf [("x", .int (-3))]) (Cond.cmp "x" .eq (.int (-3))) == true  -- case 15: when x == -3
#guard evalCond (readingOf [("x", .int 0)]) (Cond.cmp "x" .ne (.int (-3))) == true  -- case 16: when x != -3
#guard evalCond (readingOf [("x", .int (-1))]) (Cond.mem "x" [.int (-3), .int (-1), .int 2]) == true  -- case 18: when x in [-3, -1, 2]
#guard evalCond (readingOf [("x", .int 0)]) (Cond.mem "x" [.int (-3), .int (-1), .int 2]) == false  -- case 19: when x in [-3, -1, 2]
#guard evalCond (readingOf [("x", .int 3)]) (Cond.and (Cond.cmp "x" .gt (.int 1)) (Cond.cmp "x" .lt (.int 5))) == true  -- case 28: when 1 < x < 5
#guard evalCond (readingOf [("x", .int 7)]) (Cond.and (Cond.cmp "x" .gt (.int 1)) (Cond.cmp "x" .lt (.int 5))) == false  -- case 29: when 1 < x < 5
#guard evalCond (readingOf [("a", .str "watch")]) (Cond.mem "a" [.str "contain", .str "watch"]) == true  -- case 34: when a in ["contain", "watch"]
#guard evalCond (readingOf [("a", .str "contain")]) (Cond.mem "a" [.str "contain", .str "watch"]) == true  -- case 35: when a in ("contain", "watch")
#guard evalCond (readingOf [("x", .int 1)]) (Cond.mem "x" []) == false  -- case 38: when x in ()
#guard evalCond (readingOf [("s", .str "")]) (Cond.truthy "s") == false  -- case 43: when s
#guard evalCond (readingOf [("ok", .bool true), ("s", .str "x")]) (Cond.and (Cond.truthy "s") (Cond.truthy "ok")) == true  -- case 44: when s and ok
#guard evalCond (readingOf [("match", .int 1)]) (Cond.cmp "match" .eq (.int 1)) == true  -- case 47: when match == 1
#guard evalCond (readingOf [("type", .str "a")]) (Cond.cmp "type" .eq (.str "a")) == true  -- case 48: when type == 'a'
#guard evalCond (readingOf [("x", .int 1)]) (Cond.truthy "x") == true  -- case 49: when ((((((((((x))))))))))
#guard evalCond (readingOf [("a", .int 0), ("b", .int 1), ("c", .int 1)]) (Cond.and (Cond.or (Cond.truthy "a") (Cond.truthy "b")) (Cond.truthy "c")) == true  -- case 50: when (a or b) and c
#guard evalCond (readingOf [("n", .int 16)]) (Cond.cmp "n" .eq (.int 16)) == true  -- case 53: when n == 0x10
#guard evalCond (readingOf [("n", .int 15)]) (Cond.cmp "n" .eq (.int 15)) == true  -- case 54: when n == 0o17
#guard evalCond (readingOf [("n", .int 5)]) (Cond.cmp "n" .eq (.int 5)) == true  -- case 55: when n == 0b101
#guard evalCond (readingOf [("n", .int 1000)]) (Cond.cmp "n" .eq (.int 1000)) == true  -- case 56: when n == 1_000
#guard evalCond (readingOf [("x", .str "A")]) (Cond.cmp "x" .eq (.str "A")) == true  -- case 58: when x == "\x41"
#guard evalCond (readingOf [("x", .str "A")]) (Cond.cmp "x" .eq (.str "A")) == true  -- case 59: when x == "\u0041"
#guard evalCond (readingOf [("x", .str "\\n")]) (Cond.cmp "x" .eq (.str "\\n")) == true  -- case 60: when x == r'\n'
#guard evalCond (readingOf [("x", .str "a\\qb")]) (Cond.cmp "x" .eq (.str "a\\qb")) == true  -- case 61: when x == "a\qb"
#guard evalCond (readingOf [("x", .int 5)]) (Cond.cmp "x" .gt (.int (-1))) == true  -- case 69: when -1 < x
#guard evalCond (readingOf []) Cond.tt == true  -- case 72: always
#guard evalCond (readingOf []) Cond.tt == true  -- case 73: else
#guard evalCond (readingOf [("items", .int 2)]) (Cond.cmp "items" .ge (.int 10)) == false  -- case 99: when 10 <= items
#guard evalCond (readingOf [("score", .int 1)]) (Cond.not (Cond.mem "score" [])) == true  -- case 595: when not score in []
#guard evalCond (readingOf [("items", .int 10)]) (Cond.cmp "items" .lt (.int 1000)) == true  -- case 896: when 1000 > items
#guard evalCond (readingOf [("action", .str "café")]) (Cond.not (Cond.cmp "action" .eq (.str "error happened"))) == true  -- case 948: when not action == 'error happened'

/-! ## decisions.json (version 2, 7 flows): routes and canonical symbols against the reference quantizer -/
def incident_severity_all : Policy String := [⟨(Cond.truthy "data_at_risk"), "sev1_page"⟩, ⟨(Cond.and (Cond.truthy "user_facing") (Cond.cmp "error_rate" .ge (.int 25))), "sev1_page"⟩, ⟨(Cond.and (Cond.truthy "user_facing") (Cond.cmp "error_rate" .ge (.int 5))), "sev2_oncall"⟩, ⟨(Cond.cmp "error_rate" .ge (.int 1)), "sev3_ticket"⟩, ⟨Cond.tt, "watch"⟩]
def incident_severity_assess : Policy String := [⟨(Cond.truthy "data_at_risk"), "sev1_page"⟩, ⟨(Cond.and (Cond.truthy "user_facing") (Cond.cmp "error_rate" .ge (.int 25))), "sev1_page"⟩, ⟨(Cond.and (Cond.truthy "user_facing") (Cond.cmp "error_rate" .ge (.int 5))), "sev2_oncall"⟩, ⟨(Cond.cmp "error_rate" .ge (.int 1)), "sev3_ticket"⟩, ⟨Cond.tt, "watch"⟩]
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool false), ("error_rate", .int 0), ("user_facing", .bool false)]) == some "watch"  -- incident_severity reading 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 0), ("user_facing", .bool false)])).lookup "data_at_risk" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 0), ("user_facing", .bool false)])).lookup "error_rate" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 0), ("user_facing", .bool false)])).lookup "user_facing" == some 0
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool false), ("error_rate", .int 0), ("user_facing", .bool true)]) == some "watch"  -- incident_severity reading 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 0), ("user_facing", .bool true)])).lookup "data_at_risk" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 0), ("user_facing", .bool true)])).lookup "error_rate" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 0), ("user_facing", .bool true)])).lookup "user_facing" == some 1
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool false), ("error_rate", .int 1), ("user_facing", .bool false)]) == some "sev3_ticket"  -- incident_severity reading 2
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 1), ("user_facing", .bool false)])).lookup "data_at_risk" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 1), ("user_facing", .bool false)])).lookup "error_rate" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 1), ("user_facing", .bool false)])).lookup "user_facing" == some 0
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool false), ("error_rate", .int 1), ("user_facing", .bool true)]) == some "sev3_ticket"  -- incident_severity reading 3
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 1), ("user_facing", .bool true)])).lookup "data_at_risk" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 1), ("user_facing", .bool true)])).lookup "error_rate" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 1), ("user_facing", .bool true)])).lookup "user_facing" == some 1
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool false), ("error_rate", .int 4), ("user_facing", .bool false)]) == some "sev3_ticket"  -- incident_severity reading 4
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 4), ("user_facing", .bool false)])).lookup "data_at_risk" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 4), ("user_facing", .bool false)])).lookup "error_rate" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 4), ("user_facing", .bool false)])).lookup "user_facing" == some 0
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool false), ("error_rate", .int 4), ("user_facing", .bool true)]) == some "sev3_ticket"  -- incident_severity reading 5
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 4), ("user_facing", .bool true)])).lookup "data_at_risk" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 4), ("user_facing", .bool true)])).lookup "error_rate" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 4), ("user_facing", .bool true)])).lookup "user_facing" == some 1
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool false), ("error_rate", .int 5), ("user_facing", .bool false)]) == some "sev3_ticket"  -- incident_severity reading 6
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 5), ("user_facing", .bool false)])).lookup "data_at_risk" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 5), ("user_facing", .bool false)])).lookup "error_rate" == some 2
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 5), ("user_facing", .bool false)])).lookup "user_facing" == some 0
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool false), ("error_rate", .int 5), ("user_facing", .bool true)]) == some "sev2_oncall"  -- incident_severity reading 7
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 5), ("user_facing", .bool true)])).lookup "data_at_risk" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 5), ("user_facing", .bool true)])).lookup "error_rate" == some 2
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 5), ("user_facing", .bool true)])).lookup "user_facing" == some 1
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool false), ("error_rate", .int 24), ("user_facing", .bool false)]) == some "sev3_ticket"  -- incident_severity reading 8
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 24), ("user_facing", .bool false)])).lookup "data_at_risk" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 24), ("user_facing", .bool false)])).lookup "error_rate" == some 2
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 24), ("user_facing", .bool false)])).lookup "user_facing" == some 0
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool false), ("error_rate", .int 24), ("user_facing", .bool true)]) == some "sev2_oncall"  -- incident_severity reading 9
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 24), ("user_facing", .bool true)])).lookup "data_at_risk" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 24), ("user_facing", .bool true)])).lookup "error_rate" == some 2
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 24), ("user_facing", .bool true)])).lookup "user_facing" == some 1
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool false), ("error_rate", .int 25), ("user_facing", .bool false)]) == some "sev3_ticket"  -- incident_severity reading 10
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 25), ("user_facing", .bool false)])).lookup "data_at_risk" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 25), ("user_facing", .bool false)])).lookup "error_rate" == some 3
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 25), ("user_facing", .bool false)])).lookup "user_facing" == some 0
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool false), ("error_rate", .int 25), ("user_facing", .bool true)]) == some "sev1_page"  -- incident_severity reading 11
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 25), ("user_facing", .bool true)])).lookup "data_at_risk" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 25), ("user_facing", .bool true)])).lookup "error_rate" == some 3
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool false), ("error_rate", .int 25), ("user_facing", .bool true)])).lookup "user_facing" == some 1
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool true), ("error_rate", .int 0), ("user_facing", .bool false)]) == some "sev1_page"  -- incident_severity reading 12
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 0), ("user_facing", .bool false)])).lookup "data_at_risk" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 0), ("user_facing", .bool false)])).lookup "error_rate" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 0), ("user_facing", .bool false)])).lookup "user_facing" == some 0
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool true), ("error_rate", .int 0), ("user_facing", .bool true)]) == some "sev1_page"  -- incident_severity reading 13
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 0), ("user_facing", .bool true)])).lookup "data_at_risk" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 0), ("user_facing", .bool true)])).lookup "error_rate" == some 0
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 0), ("user_facing", .bool true)])).lookup "user_facing" == some 1
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool true), ("error_rate", .int 1), ("user_facing", .bool false)]) == some "sev1_page"  -- incident_severity reading 14
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 1), ("user_facing", .bool false)])).lookup "data_at_risk" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 1), ("user_facing", .bool false)])).lookup "error_rate" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 1), ("user_facing", .bool false)])).lookup "user_facing" == some 0
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool true), ("error_rate", .int 1), ("user_facing", .bool true)]) == some "sev1_page"  -- incident_severity reading 15
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 1), ("user_facing", .bool true)])).lookup "data_at_risk" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 1), ("user_facing", .bool true)])).lookup "error_rate" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 1), ("user_facing", .bool true)])).lookup "user_facing" == some 1
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool true), ("error_rate", .int 4), ("user_facing", .bool false)]) == some "sev1_page"  -- incident_severity reading 16
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 4), ("user_facing", .bool false)])).lookup "data_at_risk" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 4), ("user_facing", .bool false)])).lookup "error_rate" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 4), ("user_facing", .bool false)])).lookup "user_facing" == some 0
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool true), ("error_rate", .int 4), ("user_facing", .bool true)]) == some "sev1_page"  -- incident_severity reading 17
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 4), ("user_facing", .bool true)])).lookup "data_at_risk" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 4), ("user_facing", .bool true)])).lookup "error_rate" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 4), ("user_facing", .bool true)])).lookup "user_facing" == some 1
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool true), ("error_rate", .int 5), ("user_facing", .bool false)]) == some "sev1_page"  -- incident_severity reading 18
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 5), ("user_facing", .bool false)])).lookup "data_at_risk" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 5), ("user_facing", .bool false)])).lookup "error_rate" == some 2
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 5), ("user_facing", .bool false)])).lookup "user_facing" == some 0
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool true), ("error_rate", .int 5), ("user_facing", .bool true)]) == some "sev1_page"  -- incident_severity reading 19
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 5), ("user_facing", .bool true)])).lookup "data_at_risk" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 5), ("user_facing", .bool true)])).lookup "error_rate" == some 2
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 5), ("user_facing", .bool true)])).lookup "user_facing" == some 1
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool true), ("error_rate", .int 24), ("user_facing", .bool false)]) == some "sev1_page"  -- incident_severity reading 20
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 24), ("user_facing", .bool false)])).lookup "data_at_risk" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 24), ("user_facing", .bool false)])).lookup "error_rate" == some 2
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 24), ("user_facing", .bool false)])).lookup "user_facing" == some 0
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool true), ("error_rate", .int 24), ("user_facing", .bool true)]) == some "sev1_page"  -- incident_severity reading 21
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 24), ("user_facing", .bool true)])).lookup "data_at_risk" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 24), ("user_facing", .bool true)])).lookup "error_rate" == some 2
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 24), ("user_facing", .bool true)])).lookup "user_facing" == some 1
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool true), ("error_rate", .int 25), ("user_facing", .bool false)]) == some "sev1_page"  -- incident_severity reading 22
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 25), ("user_facing", .bool false)])).lookup "data_at_risk" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 25), ("user_facing", .bool false)])).lookup "error_rate" == some 3
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 25), ("user_facing", .bool false)])).lookup "user_facing" == some 0
#guard route incident_severity_assess (readingOf [("data_at_risk", .bool true), ("error_rate", .int 25), ("user_facing", .bool true)]) == some "sev1_page"  -- incident_severity reading 23
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 25), ("user_facing", .bool true)])).lookup "data_at_risk" == some 1
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 25), ("user_facing", .bool true)])).lookup "error_rate" == some 3
#guard (quantize (buildPartitions incident_severity_all) (readingOf [("data_at_risk", .bool true), ("error_rate", .int 25), ("user_facing", .bool true)])).lookup "user_facing" == some 1
def cat_all : Policy String := [⟨(Cond.cmp "kind" .eq (.str "urgent")), "urgent"⟩, ⟨(Cond.mem "kind" [.str "nightly", .str "weekly"]), "batch"⟩, ⟨(Cond.cmp "status" .ne (.str "ok")), "blocked"⟩, ⟨Cond.tt, "normal"⟩]
def cat_classify : Policy String := [⟨(Cond.cmp "kind" .eq (.str "urgent")), "urgent"⟩, ⟨(Cond.mem "kind" [.str "nightly", .str "weekly"]), "batch"⟩, ⟨(Cond.cmp "status" .ne (.str "ok")), "blocked"⟩, ⟨Cond.tt, "normal"⟩]
#guard route cat_classify (readingOf [("kind", .str "urgent"), ("status", .str "ok")]) == some "urgent"  -- cat reading 0
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "urgent"), ("status", .str "ok")])).lookup "kind" == some 0
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "urgent"), ("status", .str "ok")])).lookup "status" == some 0
#guard route cat_classify (readingOf [("kind", .str "urgent"), ("status", .str "__unlisted__")]) == some "urgent"  -- cat reading 1
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "urgent"), ("status", .str "__unlisted__")])).lookup "kind" == some 0
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "urgent"), ("status", .str "__unlisted__")])).lookup "status" == some 1
#guard route cat_classify (readingOf [("kind", .str "nightly"), ("status", .str "ok")]) == some "batch"  -- cat reading 2
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "nightly"), ("status", .str "ok")])).lookup "kind" == some 1
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "nightly"), ("status", .str "ok")])).lookup "status" == some 0
#guard route cat_classify (readingOf [("kind", .str "nightly"), ("status", .str "__unlisted__")]) == some "batch"  -- cat reading 3
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "nightly"), ("status", .str "__unlisted__")])).lookup "kind" == some 1
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "nightly"), ("status", .str "__unlisted__")])).lookup "status" == some 1
#guard route cat_classify (readingOf [("kind", .str "weekly"), ("status", .str "ok")]) == some "batch"  -- cat reading 4
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "weekly"), ("status", .str "ok")])).lookup "kind" == some 2
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "weekly"), ("status", .str "ok")])).lookup "status" == some 0
#guard route cat_classify (readingOf [("kind", .str "weekly"), ("status", .str "__unlisted__")]) == some "batch"  -- cat reading 5
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "weekly"), ("status", .str "__unlisted__")])).lookup "kind" == some 2
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "weekly"), ("status", .str "__unlisted__")])).lookup "status" == some 1
#guard route cat_classify (readingOf [("kind", .str "__unlisted__"), ("status", .str "ok")]) == some "normal"  -- cat reading 6
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "__unlisted__"), ("status", .str "ok")])).lookup "kind" == some 3
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "__unlisted__"), ("status", .str "ok")])).lookup "status" == some 0
#guard route cat_classify (readingOf [("kind", .str "__unlisted__"), ("status", .str "__unlisted__")]) == some "blocked"  -- cat reading 7
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "__unlisted__"), ("status", .str "__unlisted__")])).lookup "kind" == some 3
#guard (quantize (buildPartitions cat_all) (readingOf [("kind", .str "__unlisted__"), ("status", .str "__unlisted__")])).lookup "status" == some 1
def numeq_all : Policy String := [⟨(Cond.cmp "x" .eq (.int 5)), "exact"⟩, ⟨(Cond.cmp "x" .ge (.int 10)), "high"⟩, ⟨Cond.tt, "low"⟩]
def numeq_classify : Policy String := [⟨(Cond.cmp "x" .eq (.int 5)), "exact"⟩, ⟨(Cond.cmp "x" .ge (.int 10)), "high"⟩, ⟨Cond.tt, "low"⟩]
#guard route numeq_classify (readingOf [("x", .int 4)]) == some "low"  -- numeq reading 0
#guard (quantize (buildPartitions numeq_all) (readingOf [("x", .int 4)])).lookup "x" == some 0
#guard route numeq_classify (readingOf [("x", .int 5)]) == some "exact"  -- numeq reading 1
#guard (quantize (buildPartitions numeq_all) (readingOf [("x", .int 5)])).lookup "x" == some 1
#guard route numeq_classify (readingOf [("x", .int 6)]) == some "low"  -- numeq reading 2
#guard (quantize (buildPartitions numeq_all) (readingOf [("x", .int 6)])).lookup "x" == some 2
#guard route numeq_classify (readingOf [("x", .int 9)]) == some "low"  -- numeq reading 3
#guard (quantize (buildPartitions numeq_all) (readingOf [("x", .int 9)])).lookup "x" == some 2
#guard route numeq_classify (readingOf [("x", .int 10)]) == some "high"  -- numeq reading 4
#guard (quantize (buildPartitions numeq_all) (readingOf [("x", .int 10)])).lookup "x" == some 3
def pipeline_all : Policy String := [⟨(Cond.cmp "size" .gt (.int 1000)), "reject"⟩, ⟨Cond.tt, "triage"⟩, ⟨(Cond.cmp "priority" .ge (.int 8)), "urgent"⟩, ⟨(Cond.mem "kind" [.str "nightly", .str "weekly"]), "batch"⟩, ⟨Cond.tt, "normal"⟩]
def pipeline_intake : Policy String := [⟨(Cond.cmp "size" .gt (.int 1000)), "reject"⟩, ⟨Cond.tt, "triage"⟩]
def pipeline_triage : Policy String := [⟨(Cond.cmp "priority" .ge (.int 8)), "urgent"⟩, ⟨(Cond.mem "kind" [.str "nightly", .str "weekly"]), "batch"⟩, ⟨Cond.tt, "normal"⟩]
#guard route pipeline_intake (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 999)]) == some "triage"  -- pipeline reading 0
#guard route pipeline_triage (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 999)]) == some "batch"  -- pipeline reading 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 999)])).lookup "kind" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 999)])).lookup "priority" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 999)])).lookup "size" == some 0
#guard route pipeline_intake (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 1000)]) == some "triage"  -- pipeline reading 1
#guard route pipeline_triage (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 1000)]) == some "batch"  -- pipeline reading 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 1000)])).lookup "kind" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 1000)])).lookup "priority" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 1000)])).lookup "size" == some 0
#guard route pipeline_intake (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 1001)]) == some "reject"  -- pipeline reading 2
#guard route pipeline_triage (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 1001)]) == some "batch"  -- pipeline reading 2
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 1001)])).lookup "kind" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 1001)])).lookup "priority" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 7), ("size", .int 1001)])).lookup "size" == some 1
#guard route pipeline_intake (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 999)]) == some "triage"  -- pipeline reading 3
#guard route pipeline_triage (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 999)]) == some "urgent"  -- pipeline reading 3
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 999)])).lookup "kind" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 999)])).lookup "priority" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 999)])).lookup "size" == some 0
#guard route pipeline_intake (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 1000)]) == some "triage"  -- pipeline reading 4
#guard route pipeline_triage (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 1000)]) == some "urgent"  -- pipeline reading 4
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 1000)])).lookup "kind" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 1000)])).lookup "priority" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 1000)])).lookup "size" == some 0
#guard route pipeline_intake (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 1001)]) == some "reject"  -- pipeline reading 5
#guard route pipeline_triage (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 1001)]) == some "urgent"  -- pipeline reading 5
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 1001)])).lookup "kind" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 1001)])).lookup "priority" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "nightly"), ("priority", .int 8), ("size", .int 1001)])).lookup "size" == some 1
#guard route pipeline_intake (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 999)]) == some "triage"  -- pipeline reading 6
#guard route pipeline_triage (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 999)]) == some "batch"  -- pipeline reading 6
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 999)])).lookup "kind" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 999)])).lookup "priority" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 999)])).lookup "size" == some 0
#guard route pipeline_intake (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 1000)]) == some "triage"  -- pipeline reading 7
#guard route pipeline_triage (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 1000)]) == some "batch"  -- pipeline reading 7
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 1000)])).lookup "kind" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 1000)])).lookup "priority" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 1000)])).lookup "size" == some 0
#guard route pipeline_intake (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 1001)]) == some "reject"  -- pipeline reading 8
#guard route pipeline_triage (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 1001)]) == some "batch"  -- pipeline reading 8
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 1001)])).lookup "kind" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 1001)])).lookup "priority" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 7), ("size", .int 1001)])).lookup "size" == some 1
#guard route pipeline_intake (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 999)]) == some "triage"  -- pipeline reading 9
#guard route pipeline_triage (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 999)]) == some "urgent"  -- pipeline reading 9
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 999)])).lookup "kind" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 999)])).lookup "priority" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 999)])).lookup "size" == some 0
#guard route pipeline_intake (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 1000)]) == some "triage"  -- pipeline reading 10
#guard route pipeline_triage (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 1000)]) == some "urgent"  -- pipeline reading 10
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 1000)])).lookup "kind" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 1000)])).lookup "priority" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 1000)])).lookup "size" == some 0
#guard route pipeline_intake (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 1001)]) == some "reject"  -- pipeline reading 11
#guard route pipeline_triage (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 1001)]) == some "urgent"  -- pipeline reading 11
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 1001)])).lookup "kind" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 1001)])).lookup "priority" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "weekly"), ("priority", .int 8), ("size", .int 1001)])).lookup "size" == some 1
#guard route pipeline_intake (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 999)]) == some "triage"  -- pipeline reading 12
#guard route pipeline_triage (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 999)]) == some "normal"  -- pipeline reading 12
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 999)])).lookup "kind" == some 2
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 999)])).lookup "priority" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 999)])).lookup "size" == some 0
#guard route pipeline_intake (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 1000)]) == some "triage"  -- pipeline reading 13
#guard route pipeline_triage (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 1000)]) == some "normal"  -- pipeline reading 13
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 1000)])).lookup "kind" == some 2
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 1000)])).lookup "priority" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 1000)])).lookup "size" == some 0
#guard route pipeline_intake (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 1001)]) == some "reject"  -- pipeline reading 14
#guard route pipeline_triage (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 1001)]) == some "normal"  -- pipeline reading 14
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 1001)])).lookup "kind" == some 2
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 1001)])).lookup "priority" == some 0
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 7), ("size", .int 1001)])).lookup "size" == some 1
#guard route pipeline_intake (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 999)]) == some "triage"  -- pipeline reading 15
#guard route pipeline_triage (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 999)]) == some "urgent"  -- pipeline reading 15
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 999)])).lookup "kind" == some 2
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 999)])).lookup "priority" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 999)])).lookup "size" == some 0
#guard route pipeline_intake (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 1000)]) == some "triage"  -- pipeline reading 16
#guard route pipeline_triage (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 1000)]) == some "urgent"  -- pipeline reading 16
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 1000)])).lookup "kind" == some 2
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 1000)])).lookup "priority" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 1000)])).lookup "size" == some 0
#guard route pipeline_intake (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 1001)]) == some "reject"  -- pipeline reading 17
#guard route pipeline_triage (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 1001)]) == some "urgent"  -- pipeline reading 17
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 1001)])).lookup "kind" == some 2
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 1001)])).lookup "priority" == some 1
#guard (quantize (buildPartitions pipeline_all) (readingOf [("kind", .str "__unlisted__"), ("priority", .int 8), ("size", .int 1001)])).lookup "size" == some 1
def numin_all : Policy String := [⟨(Cond.mem "x" [.int 3, .int 5]), "listed"⟩, ⟨(Cond.nmem "x" [.int 7, .int 9]), "excluded"⟩, ⟨Cond.tt, "rest"⟩]
def numin_classify : Policy String := [⟨(Cond.mem "x" [.int 3, .int 5]), "listed"⟩, ⟨(Cond.nmem "x" [.int 7, .int 9]), "excluded"⟩, ⟨Cond.tt, "rest"⟩]
#guard route numin_classify (readingOf [("x", .int 2)]) == some "excluded"  -- numin reading 0
#guard (quantize (buildPartitions numin_all) (readingOf [("x", .int 2)])).lookup "x" == some 0
#guard route numin_classify (readingOf [("x", .int 3)]) == some "listed"  -- numin reading 1
#guard (quantize (buildPartitions numin_all) (readingOf [("x", .int 3)])).lookup "x" == some 1
#guard route numin_classify (readingOf [("x", .int 4)]) == some "excluded"  -- numin reading 2
#guard (quantize (buildPartitions numin_all) (readingOf [("x", .int 4)])).lookup "x" == some 2
#guard route numin_classify (readingOf [("x", .int 5)]) == some "listed"  -- numin reading 3
#guard (quantize (buildPartitions numin_all) (readingOf [("x", .int 5)])).lookup "x" == some 3
#guard route numin_classify (readingOf [("x", .int 6)]) == some "excluded"  -- numin reading 4
#guard (quantize (buildPartitions numin_all) (readingOf [("x", .int 6)])).lookup "x" == some 4
#guard route numin_classify (readingOf [("x", .int 7)]) == some "rest"  -- numin reading 5
#guard (quantize (buildPartitions numin_all) (readingOf [("x", .int 7)])).lookup "x" == some 5
#guard route numin_classify (readingOf [("x", .int 8)]) == some "excluded"  -- numin reading 6
#guard (quantize (buildPartitions numin_all) (readingOf [("x", .int 8)])).lookup "x" == some 6
#guard route numin_classify (readingOf [("x", .int 9)]) == some "rest"  -- numin reading 7
#guard (quantize (buildPartitions numin_all) (readingOf [("x", .int 9)])).lookup "x" == some 7
#guard route numin_classify (readingOf [("x", .int 10)]) == some "excluded"  -- numin reading 8
#guard (quantize (buildPartitions numin_all) (readingOf [("x", .int 10)])).lookup "x" == some 8
def truthynum_all : Policy String := [⟨(Cond.cmp "x" .ge (.int 5)), "high"⟩, ⟨(Cond.truthy "x"), "nonzero"⟩, ⟨Cond.tt, "zero"⟩]
def truthynum_classify : Policy String := [⟨(Cond.cmp "x" .ge (.int 5)), "high"⟩, ⟨(Cond.truthy "x"), "nonzero"⟩, ⟨Cond.tt, "zero"⟩]
#guard route truthynum_classify (readingOf [("x", .int (-1))]) == some "nonzero"  -- truthynum reading 0
#guard (quantize (buildPartitions truthynum_all) (readingOf [("x", .int (-1))])).lookup "x" == some 0
#guard route truthynum_classify (readingOf [("x", .int 0)]) == some "zero"  -- truthynum reading 1
#guard (quantize (buildPartitions truthynum_all) (readingOf [("x", .int 0)])).lookup "x" == some 1
#guard route truthynum_classify (readingOf [("x", .int 1)]) == some "nonzero"  -- truthynum reading 2
#guard (quantize (buildPartitions truthynum_all) (readingOf [("x", .int 1)])).lookup "x" == some 2
#guard route truthynum_classify (readingOf [("x", .int 4)]) == some "nonzero"  -- truthynum reading 3
#guard (quantize (buildPartitions truthynum_all) (readingOf [("x", .int 4)])).lookup "x" == some 2
#guard route truthynum_classify (readingOf [("x", .int 5)]) == some "high"  -- truthynum reading 4
#guard (quantize (buildPartitions truthynum_all) (readingOf [("x", .int 5)])).lookup "x" == some 3
def strtruthy_all : Policy String := [⟨(Cond.cmp "name" .eq (.str "root")), "root"⟩, ⟨(Cond.truthy "name"), "named"⟩, ⟨Cond.tt, "anonymous"⟩]
def strtruthy_classify : Policy String := [⟨(Cond.cmp "name" .eq (.str "root")), "root"⟩, ⟨(Cond.truthy "name"), "named"⟩, ⟨Cond.tt, "anonymous"⟩]
#guard route strtruthy_classify (readingOf [("name", .str "root")]) == some "root"  -- strtruthy reading 0
#guard (quantize (buildPartitions strtruthy_all) (readingOf [("name", .str "root")])).lookup "name" == some 0
#guard route strtruthy_classify (readingOf [("name", .str "")]) == some "anonymous"  -- strtruthy reading 1
#guard (quantize (buildPartitions strtruthy_all) (readingOf [("name", .str "")])).lookup "name" == some 1
#guard route strtruthy_classify (readingOf [("name", .str "__unlisted__")]) == some "named"  -- strtruthy reading 2
#guard (quantize (buildPartitions strtruthy_all) (readingOf [("name", .str "__unlisted__")])).lookup "name" == some 2

/-! ## spiral_fusion.json (34 probes at node correlate) -/
def fusion_correlate : Policy String := [⟨(Cond.and (Cond.cmp "stability" .eq (.str "shaken")) (Cond.cmp "rule_level" .ge (.int 12))), "coincident_critical"⟩, ⟨(Cond.and (Cond.cmp "stability" .eq (.str "shaken")) (Cond.cmp "soc_action" .eq (.str "contain"))), "coincident_critical"⟩, ⟨(Cond.and (Cond.cmp "dev_mg" .ge (.int 2500)) (Cond.cmp "soc_action" .eq (.str "contain"))), "coincident_critical"⟩, ⟨(Cond.and (Cond.cmp "dev_mg" .ge (.int 150)) (Cond.cmp "rule_level" .ge (.int 12))), "coincident_critical"⟩, ⟨(Cond.or (Cond.cmp "stability" .eq (.str "shaken")) (Cond.cmp "dev_mg" .ge (.int 2500))), "physical_escalation"⟩, ⟨(Cond.or (Cond.cmp "soc_action" .eq (.str "contain")) (Cond.cmp "rule_level" .ge (.int 12))), "cyber_containment"⟩, ⟨(Cond.and (Cond.cmp "stability" .eq (.str "moving")) (Cond.cmp "rule_level" .ge (.int 7))), "tandem_watch"⟩, ⟨(Cond.and (Cond.cmp "dev_mg" .ge (.int 500)) (Cond.cmp "soc_action" .eq (.str "watch"))), "tandem_watch"⟩, ⟨(Cond.or (Cond.cmp "soc_action" .eq (.str "watch")) (Cond.cmp "rule_level" .ge (.int 7))), "cyber_watch"⟩, ⟨(Cond.or (Cond.cmp "stability" .eq (.str "moving")) (Cond.cmp "dev_mg" .ge (.int 500))), "physical_watch"⟩, ⟨Cond.tt, "all_quiet"⟩]
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "all_quiet"  -- probe 0
#guard route fusion_correlate (readingOf [("dev_mg", .int 149), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "all_quiet"  -- probe 1
#guard route fusion_correlate (readingOf [("dev_mg", .int 150), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "all_quiet"  -- probe 2
#guard route fusion_correlate (readingOf [("dev_mg", .int 151), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "all_quiet"  -- probe 3
#guard route fusion_correlate (readingOf [("dev_mg", .int 499), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "all_quiet"  -- probe 4
#guard route fusion_correlate (readingOf [("dev_mg", .int 500), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "physical_watch"  -- probe 5
#guard route fusion_correlate (readingOf [("dev_mg", .int 501), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "physical_watch"  -- probe 6
#guard route fusion_correlate (readingOf [("dev_mg", .int 2499), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "physical_watch"  -- probe 7
#guard route fusion_correlate (readingOf [("dev_mg", .int 2500), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "physical_escalation"  -- probe 8
#guard route fusion_correlate (readingOf [("dev_mg", .int 2501), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "physical_escalation"  -- probe 9
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 6), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "all_quiet"  -- probe 10
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 7), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "cyber_watch"  -- probe 11
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 8), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "cyber_watch"  -- probe 12
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 11), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "cyber_watch"  -- probe 13
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 12), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "cyber_containment"  -- probe 14
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 13), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "cyber_containment"  -- probe 15
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 0), ("soc_action", .str "contain"), ("stability", .str "still")]) == some "cyber_containment"  -- probe 16
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 0), ("soc_action", .str "watch"), ("stability", .str "still")]) == some "cyber_watch"  -- probe 17
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 0), ("soc_action", .str "none"), ("stability", .str "still")]) == some "all_quiet"  -- probe 18
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "shaken")]) == some "physical_escalation"  -- probe 19
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "moving")]) == some "physical_watch"  -- probe 20
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 0), ("soc_action", .str "ignore"), ("stability", .str "On Table")]) == some "all_quiet"  -- probe 21
#guard route fusion_correlate (readingOf [("dev_mg", .int 3000), ("rule_level", .int 13), ("soc_action", .str "contain"), ("stability", .str "shaken")]) == some "coincident_critical"  -- probe 22
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 3), ("soc_action", .str "contain"), ("stability", .str "shaken")]) == some "coincident_critical"  -- probe 23
#guard route fusion_correlate (readingOf [("dev_mg", .int 3000), ("rule_level", .int 3), ("soc_action", .str "contain"), ("stability", .str "still")]) == some "coincident_critical"  -- probe 24
#guard route fusion_correlate (readingOf [("dev_mg", .int 200), ("rule_level", .int 12), ("soc_action", .str "watch"), ("stability", .str "still")]) == some "coincident_critical"  -- probe 25
#guard route fusion_correlate (readingOf [("dev_mg", .int 0), ("rule_level", .int 12), ("soc_action", .str "contain"), ("stability", .str "still")]) == some "cyber_containment"  -- probe 26
#guard route fusion_correlate (readingOf [("dev_mg", .int 149), ("rule_level", .int 12), ("soc_action", .str "contain"), ("stability", .str "still")]) == some "cyber_containment"  -- probe 27
#guard route fusion_correlate (readingOf [("dev_mg", .int 2600), ("rule_level", .int 5), ("soc_action", .str "ignore"), ("stability", .str "shaken")]) == some "physical_escalation"  -- probe 28
#guard route fusion_correlate (readingOf [("dev_mg", .int 2500), ("rule_level", .int 3), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "physical_escalation"  -- probe 29
#guard route fusion_correlate (readingOf [("dev_mg", .int 600), ("rule_level", .int 8), ("soc_action", .str "watch"), ("stability", .str "moving")]) == some "tandem_watch"  -- probe 30
#guard route fusion_correlate (readingOf [("dev_mg", .int 600), ("rule_level", .int 3), ("soc_action", .str "watch"), ("stability", .str "still")]) == some "tandem_watch"  -- probe 31
#guard route fusion_correlate (readingOf [("dev_mg", .int 100), ("rule_level", .int 3), ("soc_action", .str "ignore"), ("stability", .str "moving")]) == some "physical_watch"  -- probe 32
#guard route fusion_correlate (readingOf [("dev_mg", .int 400), ("rule_level", .int 3), ("soc_action", .str "ignore"), ("stability", .str "still")]) == some "all_quiet"  -- probe 33

/-! ## zeckendorf.py: Lean encode == reference bits for 1..300 -/
#guard FQ.Zeck.encode 1 == [true, true]
#guard FQ.Zeck.encode 2 == [false, true, true]
#guard FQ.Zeck.encode 3 == [false, false, true, true]
#guard FQ.Zeck.encode 4 == [true, false, true, true]
#guard FQ.Zeck.encode 5 == [false, false, false, true, true]
#guard FQ.Zeck.encode 6 == [true, false, false, true, true]
#guard FQ.Zeck.encode 7 == [false, true, false, true, true]
#guard FQ.Zeck.encode 8 == [false, false, false, false, true, true]
#guard FQ.Zeck.encode 9 == [true, false, false, false, true, true]
#guard FQ.Zeck.encode 10 == [false, true, false, false, true, true]
#guard FQ.Zeck.encode 11 == [false, false, true, false, true, true]
#guard FQ.Zeck.encode 12 == [true, false, true, false, true, true]
#guard FQ.Zeck.encode 13 == [false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 14 == [true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 15 == [false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 16 == [false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 17 == [true, false, true, false, false, true, true]
#guard FQ.Zeck.encode 18 == [false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 19 == [true, false, false, true, false, true, true]
#guard FQ.Zeck.encode 20 == [false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 21 == [false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 22 == [true, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 23 == [false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 24 == [false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 25 == [true, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 26 == [false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 27 == [true, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 28 == [false, true, false, true, false, false, true, true]
#guard FQ.Zeck.encode 29 == [false, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 30 == [true, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 31 == [false, true, false, false, true, false, true, true]
#guard FQ.Zeck.encode 32 == [false, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 33 == [true, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 34 == [false, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 35 == [true, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 36 == [false, true, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 37 == [false, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 38 == [true, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 39 == [false, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 40 == [true, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 41 == [false, true, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 42 == [false, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 43 == [true, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 44 == [false, true, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 45 == [false, false, true, false, true, false, false, true, true]
#guard FQ.Zeck.encode 46 == [true, false, true, false, true, false, false, true, true]
#guard FQ.Zeck.encode 47 == [false, false, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 48 == [true, false, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 49 == [false, true, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 50 == [false, false, true, false, false, true, false, true, true]
#guard FQ.Zeck.encode 51 == [true, false, true, false, false, true, false, true, true]
#guard FQ.Zeck.encode 52 == [false, false, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 53 == [true, false, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 54 == [false, true, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 55 == [false, false, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 56 == [true, false, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 57 == [false, true, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 58 == [false, false, true, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 59 == [true, false, true, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 60 == [false, false, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 61 == [true, false, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 62 == [false, true, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 63 == [false, false, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 64 == [true, false, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 65 == [false, true, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 66 == [false, false, true, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 67 == [true, false, true, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 68 == [false, false, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 69 == [true, false, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 70 == [false, true, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 71 == [false, false, true, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 72 == [true, false, true, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 73 == [false, false, false, true, false, true, false, false, true, true]
#guard FQ.Zeck.encode 74 == [true, false, false, true, false, true, false, false, true, true]
#guard FQ.Zeck.encode 75 == [false, true, false, true, false, true, false, false, true, true]
#guard FQ.Zeck.encode 76 == [false, false, false, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 77 == [true, false, false, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 78 == [false, true, false, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 79 == [false, false, true, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 80 == [true, false, true, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 81 == [false, false, false, true, false, false, true, false, true, true]
#guard FQ.Zeck.encode 82 == [true, false, false, true, false, false, true, false, true, true]
#guard FQ.Zeck.encode 83 == [false, true, false, true, false, false, true, false, true, true]
#guard FQ.Zeck.encode 84 == [false, false, false, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 85 == [true, false, false, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 86 == [false, true, false, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 87 == [false, false, true, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 88 == [true, false, true, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 89 == [false, false, false, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 90 == [true, false, false, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 91 == [false, true, false, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 92 == [false, false, true, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 93 == [true, false, true, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 94 == [false, false, false, true, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 95 == [true, false, false, true, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 96 == [false, true, false, true, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 97 == [false, false, false, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 98 == [true, false, false, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 99 == [false, true, false, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 100 == [false, false, true, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 101 == [true, false, true, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 102 == [false, false, false, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 103 == [true, false, false, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 104 == [false, true, false, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 105 == [false, false, true, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 106 == [true, false, true, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 107 == [false, false, false, true, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 108 == [true, false, false, true, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 109 == [false, true, false, true, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 110 == [false, false, false, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 111 == [true, false, false, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 112 == [false, true, false, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 113 == [false, false, true, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 114 == [true, false, true, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 115 == [false, false, false, true, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 116 == [true, false, false, true, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 117 == [false, true, false, true, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 118 == [false, false, false, false, true, false, true, false, false, true, true]
#guard FQ.Zeck.encode 119 == [true, false, false, false, true, false, true, false, false, true, true]
#guard FQ.Zeck.encode 120 == [false, true, false, false, true, false, true, false, false, true, true]
#guard FQ.Zeck.encode 121 == [false, false, true, false, true, false, true, false, false, true, true]
#guard FQ.Zeck.encode 122 == [true, false, true, false, true, false, true, false, false, true, true]
#guard FQ.Zeck.encode 123 == [false, false, false, false, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 124 == [true, false, false, false, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 125 == [false, true, false, false, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 126 == [false, false, true, false, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 127 == [true, false, true, false, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 128 == [false, false, false, true, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 129 == [true, false, false, true, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 130 == [false, true, false, true, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 131 == [false, false, false, false, true, false, false, true, false, true, true]
#guard FQ.Zeck.encode 132 == [true, false, false, false, true, false, false, true, false, true, true]
#guard FQ.Zeck.encode 133 == [false, true, false, false, true, false, false, true, false, true, true]
#guard FQ.Zeck.encode 134 == [false, false, true, false, true, false, false, true, false, true, true]
#guard FQ.Zeck.encode 135 == [true, false, true, false, true, false, false, true, false, true, true]
#guard FQ.Zeck.encode 136 == [false, false, false, false, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 137 == [true, false, false, false, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 138 == [false, true, false, false, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 139 == [false, false, true, false, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 140 == [true, false, true, false, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 141 == [false, false, false, true, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 142 == [true, false, false, true, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 143 == [false, true, false, true, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 144 == [false, false, false, false, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 145 == [true, false, false, false, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 146 == [false, true, false, false, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 147 == [false, false, true, false, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 148 == [true, false, true, false, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 149 == [false, false, false, true, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 150 == [true, false, false, true, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 151 == [false, true, false, true, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 152 == [false, false, false, false, true, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 153 == [true, false, false, false, true, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 154 == [false, true, false, false, true, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 155 == [false, false, true, false, true, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 156 == [true, false, true, false, true, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 157 == [false, false, false, false, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 158 == [true, false, false, false, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 159 == [false, true, false, false, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 160 == [false, false, true, false, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 161 == [true, false, true, false, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 162 == [false, false, false, true, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 163 == [true, false, false, true, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 164 == [false, true, false, true, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 165 == [false, false, false, false, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 166 == [true, false, false, false, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 167 == [false, true, false, false, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 168 == [false, false, true, false, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 169 == [true, false, true, false, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 170 == [false, false, false, true, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 171 == [true, false, false, true, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 172 == [false, true, false, true, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 173 == [false, false, false, false, true, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 174 == [true, false, false, false, true, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 175 == [false, true, false, false, true, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 176 == [false, false, true, false, true, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 177 == [true, false, true, false, true, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 178 == [false, false, false, false, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 179 == [true, false, false, false, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 180 == [false, true, false, false, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 181 == [false, false, true, false, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 182 == [true, false, true, false, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 183 == [false, false, false, true, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 184 == [true, false, false, true, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 185 == [false, true, false, true, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 186 == [false, false, false, false, true, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 187 == [true, false, false, false, true, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 188 == [false, true, false, false, true, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 189 == [false, false, true, false, true, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 190 == [true, false, true, false, true, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 191 == [false, false, false, false, false, true, false, true, false, false, true, true]
#guard FQ.Zeck.encode 192 == [true, false, false, false, false, true, false, true, false, false, true, true]
#guard FQ.Zeck.encode 193 == [false, true, false, false, false, true, false, true, false, false, true, true]
#guard FQ.Zeck.encode 194 == [false, false, true, false, false, true, false, true, false, false, true, true]
#guard FQ.Zeck.encode 195 == [true, false, true, false, false, true, false, true, false, false, true, true]
#guard FQ.Zeck.encode 196 == [false, false, false, true, false, true, false, true, false, false, true, true]
#guard FQ.Zeck.encode 197 == [true, false, false, true, false, true, false, true, false, false, true, true]
#guard FQ.Zeck.encode 198 == [false, true, false, true, false, true, false, true, false, false, true, true]
#guard FQ.Zeck.encode 199 == [false, false, false, false, false, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 200 == [true, false, false, false, false, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 201 == [false, true, false, false, false, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 202 == [false, false, true, false, false, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 203 == [true, false, true, false, false, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 204 == [false, false, false, true, false, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 205 == [true, false, false, true, false, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 206 == [false, true, false, true, false, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 207 == [false, false, false, false, true, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 208 == [true, false, false, false, true, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 209 == [false, true, false, false, true, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 210 == [false, false, true, false, true, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 211 == [true, false, true, false, true, false, false, false, true, false, true, true]
#guard FQ.Zeck.encode 212 == [false, false, false, false, false, true, false, false, true, false, true, true]
#guard FQ.Zeck.encode 213 == [true, false, false, false, false, true, false, false, true, false, true, true]
#guard FQ.Zeck.encode 214 == [false, true, false, false, false, true, false, false, true, false, true, true]
#guard FQ.Zeck.encode 215 == [false, false, true, false, false, true, false, false, true, false, true, true]
#guard FQ.Zeck.encode 216 == [true, false, true, false, false, true, false, false, true, false, true, true]
#guard FQ.Zeck.encode 217 == [false, false, false, true, false, true, false, false, true, false, true, true]
#guard FQ.Zeck.encode 218 == [true, false, false, true, false, true, false, false, true, false, true, true]
#guard FQ.Zeck.encode 219 == [false, true, false, true, false, true, false, false, true, false, true, true]
#guard FQ.Zeck.encode 220 == [false, false, false, false, false, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 221 == [true, false, false, false, false, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 222 == [false, true, false, false, false, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 223 == [false, false, true, false, false, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 224 == [true, false, true, false, false, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 225 == [false, false, false, true, false, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 226 == [true, false, false, true, false, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 227 == [false, true, false, true, false, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 228 == [false, false, false, false, true, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 229 == [true, false, false, false, true, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 230 == [false, true, false, false, true, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 231 == [false, false, true, false, true, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 232 == [true, false, true, false, true, false, true, false, true, false, true, true]
#guard FQ.Zeck.encode 233 == [false, false, false, false, false, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 234 == [true, false, false, false, false, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 235 == [false, true, false, false, false, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 236 == [false, false, true, false, false, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 237 == [true, false, true, false, false, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 238 == [false, false, false, true, false, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 239 == [true, false, false, true, false, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 240 == [false, true, false, true, false, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 241 == [false, false, false, false, true, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 242 == [true, false, false, false, true, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 243 == [false, true, false, false, true, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 244 == [false, false, true, false, true, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 245 == [true, false, true, false, true, false, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 246 == [false, false, false, false, false, true, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 247 == [true, false, false, false, false, true, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 248 == [false, true, false, false, false, true, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 249 == [false, false, true, false, false, true, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 250 == [true, false, true, false, false, true, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 251 == [false, false, false, true, false, true, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 252 == [true, false, false, true, false, true, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 253 == [false, true, false, true, false, true, false, false, false, false, false, true, true]
#guard FQ.Zeck.encode 254 == [false, false, false, false, false, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 255 == [true, false, false, false, false, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 256 == [false, true, false, false, false, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 257 == [false, false, true, false, false, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 258 == [true, false, true, false, false, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 259 == [false, false, false, true, false, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 260 == [true, false, false, true, false, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 261 == [false, true, false, true, false, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 262 == [false, false, false, false, true, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 263 == [true, false, false, false, true, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 264 == [false, true, false, false, true, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 265 == [false, false, true, false, true, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 266 == [true, false, true, false, true, false, true, false, false, false, false, true, true]
#guard FQ.Zeck.encode 267 == [false, false, false, false, false, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 268 == [true, false, false, false, false, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 269 == [false, true, false, false, false, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 270 == [false, false, true, false, false, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 271 == [true, false, true, false, false, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 272 == [false, false, false, true, false, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 273 == [true, false, false, true, false, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 274 == [false, true, false, true, false, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 275 == [false, false, false, false, true, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 276 == [true, false, false, false, true, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 277 == [false, true, false, false, true, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 278 == [false, false, true, false, true, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 279 == [true, false, true, false, true, false, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 280 == [false, false, false, false, false, true, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 281 == [true, false, false, false, false, true, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 282 == [false, true, false, false, false, true, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 283 == [false, false, true, false, false, true, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 284 == [true, false, true, false, false, true, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 285 == [false, false, false, true, false, true, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 286 == [true, false, false, true, false, true, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 287 == [false, true, false, true, false, true, false, true, false, false, false, true, true]
#guard FQ.Zeck.encode 288 == [false, false, false, false, false, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 289 == [true, false, false, false, false, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 290 == [false, true, false, false, false, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 291 == [false, false, true, false, false, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 292 == [true, false, true, false, false, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 293 == [false, false, false, true, false, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 294 == [true, false, false, true, false, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 295 == [false, true, false, true, false, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 296 == [false, false, false, false, true, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 297 == [true, false, false, false, true, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 298 == [false, true, false, false, true, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 299 == [false, false, true, false, true, false, false, false, true, false, false, true, true]
#guard FQ.Zeck.encode 300 == [true, false, true, false, true, false, false, false, true, false, false, true, true]

end FQ.Vectors
