#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Crystal Warden Supply Chain Labs LLC
"""Generate the spiral-node firmware's data headers from a spiral-declared flow:
`main/sidecar_blob.h` (the baked v1 sidecar, exactly what a signed pack would carry) and
`main/test_vectors.h` (boundary-probing readings: every cell's lo/hi/rep per field, full
cartesian product, plus deterministic pseudo-random fill). The host referee re-derives every
expectation from the SAME flow via the derived materialization — the device must match bit-exactly.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "adapters", "telemetry"))
sys.path.insert(0, os.path.join(HERE, "..", ".."))

import spiral as sp                      # noqa: E402
import spiral_pack as spk                # noqa: E402
from prismpath.parser import parse       # noqa: E402

FLOW = """---
name: fusion
start: decide
packing: spiral
---
## decide
-> alarm: when range < 200 and level >= 300
-> warn: when level >= 300
-> notice: when range < 200
-> ok: else
## alarm
## warn
## notice
## ok
"""
NODE = "decide"


def probes(part):
    vals = []
    for c in part.cells:
        for v in (c.get("lo"), c.get("hi"), c.get("rep")):
            if v is not None and v not in vals:
                vals.append(int(v))
    return vals


def main():
    g = parse(FLOW)
    blob = spk.serialize_layouts(g, [NODE])
    L = sp.SpiralLayout(g, NODE)

    readings = []
    grids = [probes(L.parts[f]) for f in L.fields]
    def rec(i, cur):
        if i == len(grids):
            readings.append(tuple(cur)); return
        for v in grids[i]:
            rec(i + 1, cur + [v])
    rec(0, [])
    seed = 0x5EED
    for _ in range(16):                          # deterministic xorshift fill
        row = []
        for _f in L.fields:
            seed ^= (seed << 13) & 0xFFFFFFFF
            seed ^= seed >> 17
            seed ^= (seed << 5) & 0xFFFFFFFF
            row.append(seed % 1024)
        readings.append(tuple(row))

    with open(os.path.join(HERE, "main", "sidecar_blob.h"), "w") as f:
        f.write("// GENERATED by gen_spiral_node_data.py — the baked v1 sidecar\n#pragma once\n")
        f.write("#include <stdint.h>\n")
        f.write(f"static const uint8_t SIDECAR[{len(blob)}] = {{\n")
        for i in range(0, len(blob), 12):
            f.write("  " + ", ".join(f"0x{b:02x}" for b in blob[i:i + 12]) + ",\n")
        f.write("};\n")

    with open(os.path.join(HERE, "main", "test_vectors.h"), "w") as f:
        f.write("// GENERATED by gen_spiral_node_data.py — boundary probes + deterministic fill\n")
        f.write("#pragma once\n#include <stdint.h>\n")
        f.write(f"#define TV_K {len(L.fields)}\n#define TV_N {len(readings)}\n")
        f.write(f"// field order: {', '.join(L.fields)}\n")
        f.write(f"static const int32_t TV[{len(readings)}][{len(L.fields)}] = {{\n")
        for r in readings:
            f.write("  {" + ", ".join(str(v) for v in r) + "},\n")
        f.write("};\n")

    print(f"sidecar {len(blob)}B, {len(readings)} vectors, fields={L.fields}")


if __name__ == "__main__":
    main()
