#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Crystal Warden Supply Chain Labs LLC
"""Compile the vision policy to its .ppt image and emit main/vision_policy.h: the table bytes, the field
register map, the node names, and the wire codebook (wire order and cut points per field) so the node
quantizes and encodes exactly as prismpath.telemetry does. Everything the node needs about the policy
comes from this one generated header; nothing is typed by hand.

    python gen_vision_policy.py [flow.md]
"""
import sys
from pathlib import Path
HW = Path(__file__).resolve().parent.parent; REPO = HW.parent
sys.path.insert(0, str(HW)); sys.path.insert(0, str(REPO))
import ppt_compile as pc
from prismpath.kernel.parser import parse_file
from prismpath.telemetry import quantizer as q, wire

flow = sys.argv[1] if len(sys.argv) > 1 else str(REPO.parent / "cw-strategy" / "decision-sufficient-vision" / "occupancy_6x8.md")
g = parse_file(flow)
img = pc.compile_flow(g, 25); blob = img.serialize()
parts = q.build_partitions(g); order = wire._order(parts)
names = [n for n, _ in img.nodes]
lines = ["/* generated by gen_vision_policy.py from " + Path(flow).name + " (do not edit) */", "#ifndef VISION_POLICY_H", "#define VISION_POLICY_H", "#include <stdint.h>"]
hexb = ",\n  ".join(", ".join(f"0x{b:02x}" for b in blob[i:i + 16]) for i in range(0, len(blob), 16))
lines += [f"static const uint8_t POLICY_TABLE[] = {{\n  {hexb}\n}};", f"#define POLICY_TABLE_LEN {len(blob)}",
          f"#define POLICY_N_FIELDS {len(img.fields)}", f"#define POLICY_N_NODES {len(names)}", f"#define POLICY_START {img_start}" if False else f"#define POLICY_START {names.index(g.start)}"]
lines.append("static const char *const POLICY_NODE_NAMES[] = { " + ", ".join(f'"{n}"' for n in names) + " };")
# register index by field name, for the front end to fill regs: emit as #defines REG_<name>
for name, idx in img.fields.items():
    lines.append(f"#define REG_{name} {idx}")
# the wire codebook: for each wire-order field, its register index and cut points (cell lower bounds after the first)
lines.append(f"#define WIRE_N_FIELDS {len(order)}")
maxcuts = max(len(parts[f].cells) - 1 for f in order)
lines.append(f"#define WIRE_MAX_CUTS {maxcuts}")
rows = []
for f in order:
    p = parts[f]
    if p.kind == "boolean":
        cuts = [1]                      # symbol 1 when truthy
    else:
        cuts = [c["lo"] for c in p.cells[1:]]
    cuts += [0x7fffffff] * (maxcuts - len(cuts))
    rows.append(f"  {{ REG_{f}, {len(p.cells) - 1}, {{ {', '.join(str(c) for c in cuts)} }} }}  /* {f} */")
lines.append("typedef struct { uint16_t reg; uint8_t n_cuts; int32_t cut[WIRE_MAX_CUTS]; } wire_field_t;")
lines.append("static const wire_field_t WIRE_FIELDS[WIRE_N_FIELDS] = {\n" + ",\n".join(rows) + "\n};")
lines.append("static const char *const WIRE_FIELD_NAMES[WIRE_N_FIELDS] = { " + ", ".join(f'"{f}"' for f in order) + " };")
lines.append("#endif")
Path(__file__).parent.joinpath("main", "vision_policy.h").write_text("\n".join(lines) + "\n")
print(f"vision_policy.h: table {len(blob)} B, {len(img.fields)} registers, {len(names)} nodes, start {g.start}, wire fields {len(order)}, max cuts {maxcuts}")
print("kinds:", {f: parts[f].kind for f in order if parts[f].kind != 'numeric'})
