# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Crystal Warden Supply Chain Labs LLC
"""Build OPA's WebAssembly modules for the two comparison policies with the pinned opa binary and emit
the C headers the RP2350 firmware embeds. Nothing generated here is committed: the modules are rebuilt
from systems/opa/generated/<policy>/policy.rego, and their sha256 is checked against
results/opa/evidence/A3/wasm_module_facts.json so a rebuild that drifts from the recorded module fails.

Usage: python gen_wasm.py <out_dir>          (writes <out_dir>/wasm_<policy>.h and policy_<policy>.wasm)
"""
from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
import sys
import tarfile
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
COMP = HERE.parents[1]
OPA = COMP / ".toolchain" / "bin" / "opa"
FACTS = COMP / "results" / "opa" / "evidence" / "A3" / "wasm_module_facts.json"
POLICIES = ("network_admission", "sensor_interlock")


def build(pid: str, out: Path) -> bytes:
    tmp = Path(tempfile.mkdtemp(prefix=f"opa_wasm_{pid}_"))
    (tmp / "src").mkdir()
    shutil.copy(COMP / "systems" / "opa" / "generated" / pid / "policy.rego", tmp / "src" / "policy.rego")
    subprocess.run([str(OPA), "build", "-t", "wasm", "-e", f"comparison/{pid}/decision", "-b", str(tmp / "src"),
                    "-o", str(tmp / "bundle.tar.gz")], check=True, capture_output=True)
    with tarfile.open(tmp / "bundle.tar.gz") as tf:
        member = next(m for m in tf.getmembers() if m.name.endswith("policy.wasm"))
        wasm = tf.extractfile(member).read()
    (out / f"policy_{pid}.wasm").write_bytes(wasm)
    lines = [f"/* generated by gen_wasm.py from systems/opa/generated/{pid}/policy.rego with opa build -t wasm; a third party artifact, not CW code */",
             "#include <stdint.h>", f"const uint32_t wasm_{pid}_len = {len(wasm)};", f"const uint8_t wasm_{pid}[] __attribute__((aligned(4))) = {{"]
    for i in range(0, len(wasm), 24):
        lines.append("  " + ",".join(f"0x{x:02x}" for x in wasm[i:i + 24]) + ",")
    lines.append("};")
    (out / f"wasm_{pid}.h").write_text("\n".join(lines) + "\n")
    return wasm


def main(argv=None) -> int:
    out = Path((argv or sys.argv[1:])[0]); out.mkdir(parents=True, exist_ok=True)
    facts = json.loads(FACTS.read_text()) if FACTS.exists() else {}
    recorded = facts.get("modules", {})
    drift = 0
    for pid in POLICIES:
        wasm = build(pid, out)
        digest = hashlib.sha256(wasm).hexdigest()
        rec = recorded.get(pid)
        state = "matches the recorded module" if rec and rec["sha256"] == digest else ("DRIFTS from the recorded module" if rec else "not recorded")
        if rec and rec["sha256"] != digest:
            drift += 1
        print(f"{pid}: {len(wasm)} B sha256 {digest[:16]} {state}")
    return 1 if drift else 0


if __name__ == "__main__":
    sys.exit(main())
