# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Crystal Warden Supply Chain Labs LLC
"""Build OPA's WebAssembly modules for the two comparison policies with the pinned opa binary and emit
the C headers the RP2350 firmware embeds. Nothing generated here is committed: the modules are rebuilt
from systems/opa/generated/<policy>/policy.rego. opa build embeds the source path it was given, so the
build runs from a temporary root with the fixed relative path bundle/policy.rego and is byte
reproducible; the digest is checked against the "rebuilt" digest recorded in
results/opa/evidence/A3/wasm_module_facts.json (the "as_run" digest there is the module that executed
on the board, which differs only in that embedded path), and each rebuilt module is evaluated on the
corpus through the Linux host to confirm it decides every scenario as the corpus expects.

Usage: python gen_wasm.py <out_dir>          (writes <out_dir>/wasm_<policy>.h and policy_<policy>.wasm)
"""
from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
import sys
import tarfile
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
COMP = HERE.parents[1]
OPA = COMP / ".toolchain" / "bin" / "opa"
FACTS = COMP / "results" / "opa" / "evidence" / "A3" / "wasm_module_facts.json"
POLICIES = ("network_admission", "sensor_interlock")


def build(pid: str, out: Path) -> bytes:
    tmp = Path(tempfile.mkdtemp(prefix=f"opa_wasm_{pid}_"))
    (tmp / "bundle").mkdir()
    shutil.copy(COMP / "systems" / "opa" / "generated" / pid / "policy.rego", tmp / "bundle" / "policy.rego")
    subprocess.run([str(OPA), "build", "-t", "wasm", "-e", f"comparison/{pid}/decision", "-b", "bundle",
                    "-o", "bundle.tar.gz"], check=True, capture_output=True, cwd=str(tmp))
    with tarfile.open(tmp / "bundle.tar.gz") as tf:
        member = next(m for m in tf.getmembers() if m.name.endswith("policy.wasm"))
        wasm = tf.extractfile(member).read()
    (out / f"policy_{pid}.wasm").write_bytes(wasm)
    lines = [f"/* generated by gen_wasm.py from systems/opa/generated/{pid}/policy.rego with opa build -t wasm; a third party artifact, not CW code */",
             "#include <stdint.h>", f"const uint32_t wasm_{pid}_len = {len(wasm)};", f"const uint8_t wasm_{pid}[] __attribute__((aligned(4))) = {{"]
    for i in range(0, len(wasm), 24):
        lines.append("  " + ",".join(f"0x{x:02x}" for x in wasm[i:i + 24]) + ",")
    lines.append("};")
    (out / f"wasm_{pid}.h").write_text("\n".join(lines) + "\n")
    return wasm


def corpus_check(pid: str, wasm_path: Path) -> str:
    """Run every complete corpus scenario through the Linux host; returns 'n/m identical'."""
    host = HERE / "build_linux" / "opa_host_linux"
    if not host.exists():
        return "host not built (make linux)"
    policy = json.loads((COMP / "corpus" / f"{pid}.json").read_text())
    cases = [sc for sc in policy["scenarios"] if sc.get("input") and sc.get("kind") != "undeclared_missing"
             and all(v is not None for v in sc["input"].values())]
    args = [json.dumps(sc["input"], separators=(",", ":")) for sc in cases]
    out = subprocess.run([str(host), str(wasm_path)] + args, capture_output=True, text=True).stdout.splitlines()
    results = [l for l in out if l.startswith("RESULT ")]
    ok = 0
    for sc, line in zip(cases, results):
        doc = json.loads(line.split(" ", 1)[1].rsplit(" memory", 1)[0])
        res = doc[0]["result"] if doc else {}          # an empty list is OPA's undefined: no rule matched
        got = (res.get("outcome", "no_match"), res.get("rule"))
        ok += got == (sc["expected"]["outcome"], sc["expected"].get("rule"))
    return f"{ok}/{len(cases)} identical to the corpus"


def main(argv=None) -> int:
    out = Path((argv or sys.argv[1:])[0]); out.mkdir(parents=True, exist_ok=True)
    facts = json.loads(FACTS.read_text()) if FACTS.exists() else {}
    recorded = facts.get("modules", {})
    bad = 0
    for pid in POLICIES:
        wasm = build(pid, out)
        digest = hashlib.sha256(wasm).hexdigest()
        rec = recorded.get(pid, {})
        if rec.get("rebuilt_sha256") == digest:
            state = "byte identical to the recorded rebuild"
        elif rec.get("rebuilt_sha256"):
            state = "DIFFERS from the recorded rebuild"; bad += 1
        else:
            state = "no recorded rebuild digest"
        check = corpus_check(pid, out / f"policy_{pid}.wasm")
        if "identical" in check and not check.startswith(check.split("/")[0] + "/" + check.split("/")[0]):
            bad += 1
        print(f"{pid}: {len(wasm)} B sha256 {digest[:16]} {state}; {check}")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
