# cocotb tb: the in-fabric Facet frame decoder (walker's zeck [class,tick,band] wire -> band).
#   make -f Makefile.frame
SIM ?= verilator
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES = $(PWD)/../../rtl/zeck_dec.sv $(PWD)/../../rtl/zeck_frame_rx.sv
EXTRA_ARGS += -GGAP_TICKS=100
COCOTB_TOPLEVEL = zeck_frame_rx
COCOTB_TEST_MODULES = test_zeck_frame_rx
TOPLEVEL = $(COCOTB_TOPLEVEL)
MODULE = $(COCOTB_TEST_MODULES)
include $(shell cocotb-config --makefiles)/Makefile.sim
