# cocotb tb: the wired zeck_enc -> zeck_dec codec core (peek + self-test sweep).
#   make -f Makefile.codec
SIM ?= verilator
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES = $(PWD)/../../rtl/zeck_enc.sv $(PWD)/../../rtl/zeck_dec.sv $(PWD)/../../rtl/zeck_codec_core.sv
COCOTB_TOPLEVEL = zeck_codec_core
COCOTB_TEST_MODULES = test_zeck_codec
TOPLEVEL = $(COCOTB_TOPLEVEL)
MODULE = $(COCOTB_TEST_MODULES)
include $(shell cocotb-config --makefiles)/Makefile.sim
