"""Compile the proximity policy to a .ppt and emit it as a C header for the ToF demo firmware.

The MCU decides on-device from the SAME compiler and format every other substrate uses — the table is
just baked into flash instead of streamed over serial. classify's edges, in order: 0=contact 1=near
2=mid 3=far, so the returned edge index IS the proximity band.

    python gen_proximity_table.py     # -> table_proximity.h
"""
import sys
from pathlib import Path

HW = Path(__file__).resolve().parent.parent          # prismpath-hw
REPO = HW.parent
sys.path.insert(0, str(HW))
sys.path.insert(0, str(REPO))

import ppt_compile as pc
from prismpath.parser import parse

FLOW = """---
name: proximity
start: classify
---
## classify
Distance in millimetres from the VL53L0X drives a proximity band. Real thresholds, one field.
-> contact: when dist_mm < 100
-> near: when dist_mm < 300
-> mid: when dist_mm < 800
-> far: else
## contact
-> end: when always
## near
-> end: when always
## mid
-> end: when always
## far
-> end: when always
## end
done
"""

BANDS = ["contact", "near", "mid", "far"]


def main() -> int:
    blob = pc.compile_flow(parse(FLOW), 25).serialize()
    hexb = ",\n  ".join(
        ", ".join(f"0x{b:02x}" for b in blob[i:i + 12]) for i in range(0, len(blob), 12))
    out = [
        "/* generated by gen_proximity_table.py — the embedded proximity policy .ppt (do not edit) */",
        "#ifndef TABLE_PROXIMITY_H",
        "#define TABLE_PROXIMITY_H",
        "#include <stdint.h>",
        f"static const uint8_t PROX_TABLE[] = {{\n  {hexb}\n}};",
        f"static const uint16_t PROX_TABLE_LEN = {len(blob)};",
        f'/* classify edge index -> band: {", ".join(f"{i}={b}" for i, b in enumerate(BANDS))} */',
        "#endif",
        "",
    ]
    (HW / "rp2350" / "table_proximity.h").write_text("\n".join(out))
    print(f"wrote table_proximity.h: {len(blob)} bytes, bands {BANDS}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
