# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Crystal Warden Supply Chain Labs LLC
"""Compile the knob-band policy to a .ppt and emit it as a C header for the pot-pod firmware.

One analog field (`knob`, the potentiometer's 0-4095 ADC reading) routed into four decision bands at
authored thresholds. The ESP32 decides on-device from the SAME compiler and byte-exact format every
other substrate certifies — the table is baked into flash. classify's edges, in order, ARE the band:
0=q0 1=q1 2=q2 3=q3. The onboard LED's brightness is driven by the band, so turning the knob steps the
LED through four discrete levels at exactly these constants (a decided band, not a smooth fade).

    python gen_pot_table.py     # -> main/pot_table.h
"""
import sys
from pathlib import Path

HW = Path(__file__).resolve().parent.parent          # prismpath-hw
REPO = HW.parent
sys.path.insert(0, str(HW))
sys.path.insert(0, str(REPO))

import ppt_compile as pc
from prismpath.parser import parse

FLOW = """---
name: knob
start: classify
---
## classify
Potentiometer position (0-4095 from the ADC) drives a decision band. Discrete verdicts, exact thresholds.
-> q0: when knob < 1024
-> q1: when knob < 2048
-> q2: when knob < 3072
-> q3: else
## q0
-> end: when always
## q1
-> end: when always
## q2
-> end: when always
## q3
-> end: when always
## end
done
"""

BANDS = ["q0", "q1", "q2", "q3"]


def main() -> int:
    blob = pc.compile_flow(parse(FLOW), 25).serialize()
    hexb = ",\n  ".join(
        ", ".join(f"0x{b:02x}" for b in blob[i:i + 12]) for i in range(0, len(blob), 12))
    out = [
        "/* generated by gen_pot_table.py — the embedded knob-band policy .ppt (do not edit) */",
        "#ifndef POT_TABLE_H",
        "#define POT_TABLE_H",
        "#include <stdint.h>",
        f"static const uint8_t POT_TABLE[] = {{\n  {hexb}\n}};",
        f"static const uint16_t POT_TABLE_LEN = {len(blob)};",
        f'/* classify edge index -> band: {", ".join(f"{i}={b}" for i, b in enumerate(BANDS))} '
        '(thresholds 1024/2048/3072) */',
        "#endif",
        "",
    ]
    (HW / "esp-pot-pod" / "main" / "pot_table.h").parent.mkdir(parents=True, exist_ok=True)
    (HW / "esp-pot-pod" / "main" / "pot_table.h").write_text("\n".join(out))
    print(f"wrote pot_table.h: {len(blob)} bytes, bands {BANDS} at 1024/2048/3072")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
