// ppt_ctrl_pack.svh - GENERATED by tools/gen_pack_svh.py from ctrl_table.json; do not hand-edit.
localparam int NENT = 8;
localparam logic [10:0] CTRL_TBL [0:NENT-1] = '{
    {3'd1, 8'h00},  // P0 BTN0
    {3'd1, 8'h01},  // P0 BTN1
    {3'd1, 8'h02},  // P0 BTN2
    {3'd2, 8'h81},  // P0 BTN3
    {3'd3, 8'h00},  // P1 BTN0
    {3'd4, 8'h00},  // P1 BTN1
    {3'd5, 8'h00},  // P1 BTN2
    {3'd2, 8'h00}   // P1 BTN3
};
