# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Crystal Warden Supply Chain Labs LLC
"""Compile the two pre-vetted mesh policies, SIGN them with the fleet's Ed25519 authority key, and emit
them as a C header for the ESP-NOW nodes.

Policy A (permissive) and B (tightened) both decide `level` into allow/deny; on the fixed test input
they DISAGREE, so a coordinated flip is visible as every node's verdict changing at once. Each policy
carries a monotonic `version` (A=1 permissive, B=2 tightened) and a detached Ed25519 signature over the
domain-separated message `"PPTM1" || key_id || version || len || table`. A follower stages a pushed
table only if the signature verifies against the baked authority public key AND the version exceeds its
persisted floor (anti-rollback / anti-replay). Because B's version is higher, A -> B is the legitimate
forward tighten; B -> A is a rollback the version floor rejects. This is the real cryptographic gate
the earlier FNV-1a id/allowlist stood in for (#100).

The private key lives at `authority_ed25519.key` (raw 32-byte seed, gitignored) and is created on first
run. Only the 32-byte public key is baked into the firmware.

    python gen_mesh_tables.py     # -> main/tables.h  (+ authority_ed25519.key on first run)
"""
import sys
import struct
import hashlib
from pathlib import Path

HERE = Path(__file__).resolve().parent
HW = HERE.parent
REPO = HW.parent
sys.path.insert(0, str(HW))
sys.path.insert(0, str(REPO))

import ppt_compile as pc
from prismpath.parser import parse
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives.serialization import (
    Encoding, PrivateFormat, PublicFormat, NoEncryption)

POLICY_A = """---
name: policy_a
start: classify
---
## classify
-> allow: when level < 300
-> deny: else
## allow
-> end: when always
## deny
-> end: when always
## end
done
"""
POLICY_B = POLICY_A.replace("policy_a", "policy_b").replace("level < 300", "level < 200")

TEST_LEVEL = 250      # A: 250<300 -> allow (edge 0); B: 250>=200 -> deny (edge 1)
VERSION_A = 1         # permissive baseline
VERSION_B = 2         # tightened; A->B forward, B->A is a rollback the floor rejects
KEY_PATH = HERE / "authority_ed25519.key"


def fnv1a32(b: bytes) -> int:
    h = 0x811C9DC5
    for x in b:
        h = ((h ^ x) * 0x01000193) & 0xFFFFFFFF
    return h


def carr(name, blob):
    hexb = ",\n  ".join(", ".join(f"0x{c:02x}" for c in blob[i:i + 12]) for i in range(0, len(blob), 12))
    return f"static const uint8_t {name}[] = {{\n  {hexb}\n}};"


def barr(name, data):
    return f"static const uint8_t {name}[{len(data)}] = {{ " + ", ".join(f"0x{c:02x}" for c in data) + " };"


def load_or_make_key():
    if KEY_PATH.exists():
        priv = Ed25519PrivateKey.from_private_bytes(KEY_PATH.read_bytes())
        created = False
    else:
        priv = Ed25519PrivateKey.generate()
        KEY_PATH.write_bytes(priv.private_bytes(Encoding.Raw, PrivateFormat.Raw, NoEncryption()))
        created = True
    pub = priv.public_key().public_bytes(Encoding.Raw, PublicFormat.Raw)
    return priv, pub, created


def signed_msg(key_id, version, table):
    return b"PPTM1" + key_id + struct.pack("<I", version) + struct.pack("<H", len(table)) + table


def main() -> int:
    a = pc.compile_flow(parse(POLICY_A), 25).serialize()
    b = pc.compile_flow(parse(POLICY_B), 25).serialize()
    ida, idb = fnv1a32(a), fnv1a32(b)

    priv, pub, created = load_or_make_key()
    key_id = hashlib.sha256(pub).digest()[:4]
    sig_a = priv.sign(signed_msg(key_id, VERSION_A, a))
    sig_b = priv.sign(signed_msg(key_id, VERSION_B, b))

    out = [
        "/* generated by gen_mesh_tables.py — two Ed25519-signed mesh policies + authority pubkey (do not edit) */",
        "#ifndef TABLES_H", "#define TABLES_H", "#include <stdint.h>",
        "",
        carr("TABLE_A", a), f"static const uint16_t TABLE_A_LEN = {len(a)};",
        f"static const uint32_t POLICY_ID_A = 0x{ida:08x}u;   /* identity tag (A/B display + toggle), not the security check */",
        f"static const uint32_t VERSION_A = {VERSION_A};       /* permissive baseline */",
        barr("SIG_A", sig_a),
        "",
        carr("TABLE_B", b), f"static const uint16_t TABLE_B_LEN = {len(b)};",
        f"static const uint32_t POLICY_ID_B = 0x{idb:08x}u;",
        f"static const uint32_t VERSION_B = {VERSION_B};       /* tightened; B->A is a rollback the version floor rejects */",
        barr("SIG_B", sig_b),
        "",
        "/* the fleet authority: only the public key is on-device; a pushed table is accepted only if its",
        "   Ed25519 signature verifies against this key AND its version exceeds the node's persisted floor */",
        barr("AUTHORITY_PUBKEY", pub),
        barr("KEY_ID", key_id),
        "",
        f"static const int32_t TEST_LEVEL = {TEST_LEVEL};",
        '/* classify edge index -> verdict: 0=allow 1=deny */',
        "#endif", "",
    ]
    (HERE / "main").mkdir(parents=True, exist_ok=True)
    (HERE / "main" / "tables.h").write_text("\n".join(out))
    if created:
        print(f"created authority key {KEY_PATH.name} (gitignored)")
    print(f"A={len(a)}B v{VERSION_A} id=0x{ida:08x} | B={len(b)}B v{VERSION_B} id=0x{idb:08x} | "
          f"key_id={key_id.hex()} | signed with Ed25519 authority key")
    print(f"at level={TEST_LEVEL}: A->allow(0) B->deny(1); A->B accepted (v2>v1), B->A rejected (v1<=floor)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
