"""Compile the two pre-vetted mesh policies to .ppt and emit them as a C header for the ESP-NOW nodes.

Policy A (permissive) and B (tightened) both decide `level` into allow/deny; on the fixed test input
they DISAGREE, so a coordinated flip is visible as every node's verdict changing at once. Each policy
gets a 32-bit FNV-1a id — the node's allowlist {id_A, id_B} is the on-device "pre-vetting": a PREPARE
carrying any other bytes is refused. (A real deployment swaps this id-allowlist for an Ed25519
signature check — the same shape, one layer up. Stated plainly.)

    python gen_mesh_tables.py     # -> main/tables.h
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
HW = HERE.parent
REPO = HW.parent
sys.path.insert(0, str(HW))
sys.path.insert(0, str(REPO))

import ppt_compile as pc
from prismpath.parser import parse

POLICY_A = """---
name: policy_a
start: classify
---
## classify
-> allow: when level < 300
-> deny: else
## allow
-> end: when always
## deny
-> end: when always
## end
done
"""
POLICY_B = POLICY_A.replace("policy_a", "policy_b").replace("level < 300", "level < 200")

TEST_LEVEL = 250      # A: 250<300 -> allow (edge 0); B: 250>=200 -> deny (edge 1)


def fnv1a32(b: bytes) -> int:
    h = 0x811C9DC5
    for x in b:
        h = ((h ^ x) * 0x01000193) & 0xFFFFFFFF
    return h


def carr(name, blob):
    hexb = ",\n  ".join(", ".join(f"0x{c:02x}" for c in blob[i:i + 12]) for i in range(0, len(blob), 12))
    return f"static const uint8_t {name}[] = {{\n  {hexb}\n}};"


def main() -> int:
    a = pc.compile_flow(parse(POLICY_A), 25).serialize()
    b = pc.compile_flow(parse(POLICY_B), 25).serialize()
    ida, idb = fnv1a32(a), fnv1a32(b)
    out = [
        "/* generated by gen_mesh_tables.py — the two pre-vetted mesh policies (do not edit) */",
        "#ifndef TABLES_H", "#define TABLES_H", "#include <stdint.h>",
        carr("TABLE_A", a), f"static const uint16_t TABLE_A_LEN = {len(a)};",
        f"static const uint32_t POLICY_ID_A = 0x{ida:08x}u;   /* policy_a: level<300 (permissive) */",
        carr("TABLE_B", b), f"static const uint16_t TABLE_B_LEN = {len(b)};",
        f"static const uint32_t POLICY_ID_B = 0x{idb:08x}u;   /* policy_b: level<200 (tightened) */",
        f"static const int32_t TEST_LEVEL = {TEST_LEVEL};",
        '/* classify edge index -> verdict: 0=allow 1=deny */',
        "#endif", "",
    ]
    (HERE / "main" / "tables.h").parent.mkdir(parents=True, exist_ok=True)
    (HERE / "main" / "tables.h").write_text("\n".join(out))
    print(f"A={len(a)}B id_A=0x{ida:08x} id_B=0x{idb:08x} | at level={TEST_LEVEL}: A->allow(0) B->deny(1)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
